classdef DynamicStepFactory
    %DYNAMICSTEPFACTORY Builds vibration, cable acceleration, spectra, and dynamic strain steps.

    methods (Static)
        function plan = append(plan, root, startDate, endDate, opts, cfg, statsDir, sub)
            L = @(key) bms.module.ModuleRegistry.fromKey(key).isEnabled(opts);
            D = @bms.app.StepDefinition.fromKey;

            if L('acceleration')
                plan = plan.addRun(D('acceleration'), @() analyze_acceleration_points(root, startDate, endDate, fullfile(statsDir, 'accel_stats.xlsx'), sub.accel, true, cfg));
            end
            if L('cable_accel')
                plan = plan.addRun(D('cable_accel'), @() analyze_cable_acceleration_points(root, startDate, endDate, fullfile(statsDir, 'cable_accel_stats.xlsx'), sub.cable_accel, true, cfg));
            end

            if L('accel_spectrum')
                defaultPts = {'GB-VIB-G04-001-01','GB-VIB-G05-001-01', ...
                    'GB-VIB-G05-002-01','GB-VIB-G05-003-01', ...
                    'GB-VIB-G06-001-01','GB-VIB-G06-002-01', ...
                    'GB-VIB-G06-003-01','GB-VIB-G07-001-01'};
                accelPts = bms.app.LegacyStepFunctions.getPoints(cfg, 'accel_spectrum', bms.app.LegacyStepFunctions.getPoints(cfg, 'acceleration', defaultPts));
                [freqs, tol] = bms.app.LegacyStepFunctions.getAccelSpecParams(cfg);
                plan = plan.addRun(D('accel_spectrum'), @() analyze_accel_spectrum_points(root, startDate, endDate, accelPts, fullfile(statsDir, 'accel_spec_stats.xlsx'), sub.accel_raw, freqs, tol, false, cfg));
            end

            if L('cable_accel_spectrum')
                defaultPts = {'GB-VIB-G04-001-01','GB-VIB-G05-001-01', ...
                    'GB-VIB-G05-002-01','GB-VIB-G05-003-01', ...
                    'GB-VIB-G06-001-01','GB-VIB-G06-002-01', ...
                    'GB-VIB-G06-003-01','GB-VIB-G07-001-01'};
                cablePts = bms.app.LegacyStepFunctions.getPoints(cfg, 'cable_accel_spectrum', ...
                    bms.app.LegacyStepFunctions.getPoints(cfg, 'cable_accel', bms.app.LegacyStepFunctions.getPoints(cfg, 'cable_force', defaultPts)));
                [freqs, tol] = bms.app.LegacyStepFunctions.getCableSpecParams(cfg);
                plan = plan.addRun(D('cable_accel_spectrum'), @() analyze_cable_accel_spectrum_points(root, startDate, endDate, cablePts, fullfile(statsDir, 'cable_accel_spec_stats.xlsx'), sub.cable_accel_raw, freqs, tol, false, cfg));
            end

            if L('dynamic_strain_highpass')
                plan = plan.addRun(D('dynamic_strain_highpass'), @() analyze_dynamic_strain_boxplot( ...
                    root, startDate, endDate, ...
                    'Cfg',         cfg, ...
                    'Subfolder',   sub.strain, ...
                    'OutputDir',   bms.app.LegacyStepFunctions.dynamicHighpassOutputDir(), ...
                    'Fs',          20, ...
                    'Fc',          0.1, ...
                    'Whisker',     300, ...
                    'ShowOutliers', false, ...
                    'YLimManual',  true, ...
                    'YLimRange',   [-30 30], ...
                    'LowerBound',  -150, ...
                    'UpperBound',   30, ...
                    'EdgeTrimSec',   5));
            end

            if L('dynamic_strain_lowpass')
                plan = plan.addRun(D('dynamic_strain_lowpass'), @() analyze_dynamic_strain_lowpass_boxplot(root, startDate, endDate, 'Cfg', cfg, 'Subfolder', sub.strain));
            end
        end
    end
end
