classdef FigThresholdRequestRunner
    %FIGTHRESHOLDREQUESTRUNNER Compiled interactive FIG threshold request.

    methods (Static)
        function resultPath = runFile(requestPath)
            requestPath = char(string(requestPath));
            request = bms.io.JsonFile.read(requestPath);
            required = {'schema_version', 'request_type', 'request_id', ...
                'operation', 'fig_path', 'fig_sha256', 'status_path', ...
                'result_path', 'target_module', 'target_point'};
            for i = 1:numel(required)
                if ~isfield(request, required{i}) || isempty(request.(required{i}))
                    error('BMS:FigThresholdRequest:MissingField', ...
                        'FIG threshold request missing field: %s', required{i});
                end
            end
            if ~isnumeric(request.schema_version) ...
                    || ~isscalar(request.schema_version) ...
                    || ~isfinite(request.schema_version) ...
                    || double(request.schema_version) ~= 1
                error('BMS:FigThresholdRequest:SchemaVersion', ...
                    'Unsupported FIG threshold request schema_version.');
            end
            requestType = lower(strtrim(char(string(request.request_type))));
            if ~strcmp(requestType, 'fig_threshold_interaction')
                error('BMS:FigThresholdRequest:RequestType', ...
                    'request_type must be fig_threshold_interaction.');
            end

            operation = lower(strtrim(char(string(request.operation))));
            if ~ismember(operation, {'band', 'box_lower', 'box_upper'})
                error('BMS:FigThresholdRequest:Operation', ...
                    'Unsupported FIG threshold operation: %s', operation);
            end
            statusPath = char(string(request.status_path));
            resultPath = char(string(request.result_path));
            requestId = bms.app.FigThresholdRequestRunner.textField(request, 'request_id');
            if isempty(strtrim(requestId))
                error('BMS:FigThresholdRequest:RequestId', ...
                    'request_id cannot be blank.');
            end
            targetModule = strtrim(char(string(request.target_module)));
            targetPoint = strtrim(char(string(request.target_point)));
            if isempty(targetModule) || isempty(targetPoint)
                error('BMS:FigThresholdRequest:Target', ...
                    'target_module and target_point cannot be blank.');
            end
            bms.app.AsyncRunService.writeStatus(statusPath, 'running', struct( ...
                'request_type', 'fig_threshold_interaction', ...
                'request_id', requestId, ...
                'operation', operation, ...
                'request_path', requestPath));

            try
                figPath = bms.app.FigThresholdRequestRunner.canonicalPath(request.fig_path);
                if exist(figPath, 'file') ~= 2 || ~endsWith(figPath, '.fig', 'IgnoreCase', true)
                    error('BMS:FigThresholdRequest:MissingFig', ...
                        'FIG source does not exist or is not a .fig file: %s', figPath);
                end
                expectedHash = lower(strtrim(char(string(request.fig_sha256))));
                if isempty(regexp(expectedHash, '^[0-9a-f]{64}$', 'once')) %#ok<RGXP1>
                    error('BMS:FigThresholdRequest:FigHashFormat', ...
                        'fig_sha256 must contain exactly 64 hexadecimal characters.');
                end
                sourceBefore = bms.app.FigThresholdRequestRunner.fileInfo(figPath);
                if isfield(request, 'fig_size_bytes') && ~isempty(request.fig_size_bytes)
                    expectedBytes = double(request.fig_size_bytes);
                    if ~isscalar(expectedBytes) || ~isfinite(expectedBytes) ...
                            || expectedBytes ~= sourceBefore.size
                        error('BMS:FigThresholdRequest:FigSizeChanged', ...
                            'FIG size differs from the request: %s', figPath);
                    end
                end
                actualHash = bms.io.JsonFile.sha256(figPath);
                if ~strcmp(actualHash, expectedHash)
                    error('BMS:FigThresholdRequest:FigHashChanged', ...
                        'FIG SHA-256 differs from the request: %s', figPath);
                end

                options = struct('throw_errors', true, 'point_id', targetPoint);
                if isfield(request, 'scripted_selection') ...
                        && isstruct(request.scripted_selection)
                    options.scripted_selection = request.scripted_selection;
                end
                sourceCurve = bms.gui.FigCurveSelector.metadata([]);
                switch operation
                    case 'band'
                        [rule, sourceCurve] = pick_threshold_lines_from_fig([], figPath, options);
                    case 'box_lower'
                        [rule, sourceCurve] = pick_threshold_box_from_fig( ...
                            [], figPath, 'lower', options);
                    case 'box_upper'
                        [rule, sourceCurve] = pick_threshold_box_from_fig( ...
                            [], figPath, 'upper', options);
                end

                sourceAfter = bms.app.FigThresholdRequestRunner.fileInfo(figPath);
                finalHash = bms.io.JsonFile.sha256(figPath);
                if sourceAfter.size ~= sourceBefore.size ...
                        || sourceAfter.mtime_millis ~= sourceBefore.mtime_millis ...
                        || ~strcmp(finalHash, actualHash)
                    error('BMS:FigThresholdRequest:FigChangedDuringInteraction', ...
                        'FIG changed while the threshold interaction was active: %s', figPath);
                end

                if isempty(rule)
                    resultStatus = 'cancelled';
                    candidate = struct();
                else
                    resultStatus = 'ok';
                    if strcmp(operation, 'band')
                        candidate = struct( ...
                            'lower', double(rule.min), ...
                            'upper', double(rule.max), ...
                            't_range_start', char(string(rule.t_range_start)), ...
                            't_range_end', char(string(rule.t_range_end)));
                    else
                        candidate = struct( ...
                            'side', char(string(rule.side)), ...
                            'value', double(rule.value), ...
                            'selected_sample_count', double(rule.selected_sample_count), ...
                            'selection_start', char(string(rule.selection_start)), ...
                            'selection_end', char(string(rule.selection_end)));
                    end
                end
                sourceFig = struct( ...
                    'path', figPath, ...
                    'sha256', actualHash, ...
                    'size', sourceBefore.size, ...
                    'mtime', sourceBefore.mtime);
                result = struct( ...
                    'schema_version', 1, ...
                    'artifact_type', 'fig_threshold_result', ...
                    'request_type', 'fig_threshold_interaction', ...
                    'request_id', requestId, ...
                    'status', resultStatus, ...
                    'operation', operation, ...
                    'target_module', targetModule, ...
                    'target_point', targetPoint, ...
                    'candidate', candidate, ...
                    'source_curve', sourceCurve, ...
                    'source_fig', sourceFig);
                bms.core.Logger.writeJson(resultPath, result);
                bms.app.AsyncRunService.writeStatus(statusPath, 'completed', struct( ...
                    'request_type', 'fig_threshold_interaction', ...
                    'request_id', requestId, ...
                    'operation', operation, ...
                    'request_path', requestPath, ...
                    'result_path', resultPath, ...
                    'result_status', resultStatus));
            catch ME
                bms.app.AsyncRunService.writeStatus(statusPath, 'failed', struct( ...
                    'request_type', 'fig_threshold_interaction', ...
                    'request_id', requestId, ...
                    'operation', operation, ...
                    'request_path', requestPath, ...
                    'error_id', ME.identifier, ...
                    'message', ME.message));
                rethrow(ME);
            end
        end

        function value = textField(s, field)
            value = '';
            if isstruct(s) && isfield(s, field) && ~isempty(s.(field))
                value = char(string(s.(field)));
            end
        end

        function path = canonicalPath(value)
            path = char(string(value));
            try
                path = char(java.io.File(path).getCanonicalPath());
            catch
                path = bms.profile.BridgeProfile.normalizePathText(path);
            end
        end

        function info = fileInfo(path)
            item = dir(path);
            if isempty(item) || item(1).isdir
                error('BMS:FigThresholdRequest:MissingFig', ...
                    'Cannot read FIG metadata: %s', path);
            end
            file = java.io.File(path);
            millis = double(file.lastModified());
            timestamp = datetime(millis / 1000, 'ConvertFrom', 'posixtime', ...
                'Format', "yyyy-MM-dd'T'HH:mm:ss.SSS");
            info = struct( ...
                'size', double(item(1).bytes), ...
                'mtime_millis', millis, ...
                'mtime', char(timestamp));
        end
    end
end
