%root        = 'G:\BaiduNetdiskDownload\管柄大桥数据';
root        = 'F:\BaiduNetdiskDownload';
start_date  = '2025-03-26';
end_date    = '2025-04-25';

% 这里改 true/false 来开关每一步
opts = struct( ...
    'doUnzip',         false, ...
    'doRenameCsv',     false, ...
    'doRemoveHeader',  false, ...
    'doResample',        false, ...
    'doTemp',           false, ...
    'doHumidity',       false, ...
    'doDeflect',     true, ...
    'doTilt',           false, ...
    'doAccel',        false, ...
    'doRenameCrk',     false, ...
    'doCrack',        false, ...
    'doStrain',        false  ...
);

run_all(root, start_date, end_date, opts);
