%root        = 'G:\BaiduNetdiskDownload\管柄大桥数据';
root        = 'H:\BaiduNetdiskDownload';
start_date  = '2025-03-26';
end_date    = '2025-04-25';

% 这里改 true/false 来开关每一步
opts = struct( ...
    'doUnzip',         false, ...
    'doRenameCsv',     true, ...
    'doRemoveHeader',  false, ...
    'doResample',        true, ...
    'doTemp',           true, ...
    'doHumidity',       true, ...
    'doDeflect',     true, ...
    'doTilt',           true, ...
    'doAccel',          true, ...
    'doRenameCrk',     true, ...
    'doCrack',        true, ...
    'doStrain',        true  ...
);

run_all(root, start_date, end_date, opts);
