classdef StandardVerifiedSourceCsvCleanupService
    %STANDARDVERIFIEDSOURCECSVCLEANUPSERVICE Verified cleanup for standard CSVs.
    %   Supports dated_folders and hongtang_period. Every configured CSV for
    %   one natural day is fully prepared before the first rename: its MAT
    %   cache must load independently and its exact path/size/CRC must map to
    %   one and only one verified source ZIP entry. Any preparation failure
    %   authorises zero deletions for that day.

    methods (Static)
        function result = commitDay(root, day, records, cfg, taskOptions)
            if nargin < 4, cfg = struct(); end
            if nargin < 5, taskOptions = struct(); end
            options = bms.data.VerifiedSourceCsvCleanupService. ...
                optionsFromTask(taskOptions);
            dayText = bms.data.TimeRangeResolver.toDateString(day);
            result = struct('enabled', options.enabled, 'status', 'retained', ...
                'day', dayText, 'receipt_path', '', 'deleted_count', 0, ...
                'deleted_bytes', 0);
            if ~options.enabled, return; end
            provider = bms.data.CacheSourceCleanupProvider.resolve(root, cfg);
            if ~any(strcmp(provider.layout, {'dated_folders','hongtang_period'}))
                error('BMS:CacheSourceCleanup:ProviderMismatch', ...
                    'Standard cleanup cannot process layout: %s', provider.layout);
            end
            if isempty(records)
                error('BMS:CacheSourceCleanup:NoEligibleRecords', ...
                    'No configured cache records exist for %s.', dayText);
            end
            receiptPath = bms.data.CacheSourceCleanupProvider. ...
                standardReceiptPath(root, dayText);
            bms.data.DataLayoutResolver.ensureParentDir(receiptPath);
            cleanupLockPath = ...
                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    dayLockPath(root, dayText);
            lease = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                acquireDayLease(root, dayText); %#ok<NASGU>
            if isfile(receiptPath)
                receipt = bms.io.JsonFile.read(receiptPath);
                receipt = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    resumeReceipt(receiptPath, receipt, root, cfg, taskOptions);
                result.status = char(string(receipt.status));
                result.receipt_path = receiptPath;
                result.deleted_count = double(receipt.deleted_count);
                result.deleted_bytes = double(receipt.deleted_bytes);
                return;
            end

            statuses = cellstr(string({records.status}));
            if any(~ismember(statuses, {'created','reused','rebuilt'}))
                error('BMS:CacheSourceCleanup:CacheDayIncomplete', ...
                    ['At least one configured CSV cache failed; no source file ' ...
                     'was deleted for %s.'], dayText);
            end
            sourcePaths = cellstr(string({records.path}));
            if numel(unique(lower(string(sourcePaths)))) ~= numel(sourcePaths)
                error('BMS:CacheSourceCleanup:DuplicateSource', ...
                    'Configured cache discovery contains duplicate source paths.');
            end

            % Prepare every cache identity and every archive proof before
            % publishing a receipt or renaming the first source file.
            identities = cell(1, numel(records));
            for i = 1:numel(records)
                identities{i} = bms.data.CacheSourceCleanupProvider. ...
                    validateStandardCache(records(i).path, ...
                        records(i).cache_path, cfg);
            end
            proofs = bms.data.ArchiveExtractService. ...
                verifyRecoveryGroupsForFiles(root, dayText, cfg, sourcePaths);
            entries = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                buildEntries([identities{:}], proofs);
            receiptId = char(java.util.UUID.randomUUID());
            for i = 1:numel(entries)
                [folder, base, ext] = fileparts(entries(i).source_path);
                entries(i).temporary_path = fullfile(folder, sprintf( ...
                    '.%s%s.bmsdelete.%s', base, ext, receiptId));
            end
            receipt = struct( ...
                'schema_version', 3, ...
                'receipt_type', 'verified_cache_source_cleanup', ...
                'provider_id', provider.id, ...
                'receipt_id', receiptId, ...
                'status', 'prepared', ...
                'mode', options.mode, ...
                'commit_scope', options.commit_scope, ...
                'recovery_policy', options.recovery_policy, ...
                'confirmation', options.confirmation, ...
                'confirmed_at', options.confirmed_at, ...
                'created_at', datestr(datetime('now'), ...
                    'yyyy-mm-dd HH:MM:ss'), ...
                'committed_at', '', ...
                'root', bms.data.CacheSourceCleanupProvider.canonicalPath(root), ...
                'day', dayText, ...
                'layout', provider.layout, ...
                'cache_version', provider.cache_version, ...
                'scope_hash', bms.data.CacheSourceCleanupProvider. ...
                    standardScopeHash(cfg, provider.layout, ...
                        provider.cache_version), ...
                'cleanup_lock_path', cleanupLockPath, ...
                'archive_proofs', proofs, ...
                'files', entries, ...
                'deleted_count', 0, ...
                'deleted_bytes', 0, ...
                'error_identifier', '', ...
                'error_message', '');
            receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                publishCleanupAuthorization( ...
                    receiptPath, receipt, cleanupLockPath);
            receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                publishReceipt(receiptPath, receipt);
            receipt = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                commitReceipt(receiptPath, receipt, cfg, true);
            result.status = receipt.status;
            result.receipt_path = receiptPath;
            result.deleted_count = receipt.deleted_count;
            result.deleted_bytes = receipt.deleted_bytes;
        end

        function verification = reconcilePendingDay(root, day, cfg, taskOptions)
            if nargin < 3, cfg = struct(); end
            if nargin < 4, taskOptions = struct(); end
            dayText = bms.data.TimeRangeResolver.toDateString(day);
            verification = struct('committed', false, 'day', dayText, ...
                'receipt_path', '', 'cache_count', 0, ...
                'deleted_count', 0, 'deleted_bytes', 0);
            receiptPath = bms.data.CacheSourceCleanupProvider. ...
                standardReceiptPath(root, dayText);
            if ~isfile(receiptPath), return; end
            lease = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                acquireDayLease(root, dayText); %#ok<NASGU>
            receipt = bms.io.JsonFile.read(receiptPath);
            receipt = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                resumeReceipt(receiptPath, receipt, root, cfg, taskOptions);
            if strcmp(char(string(receipt.status)), 'committed')
                verification.committed = true;
                verification.receipt_path = receiptPath;
                verification.cache_count = numel(receipt.files);
                verification.deleted_count = double(receipt.deleted_count);
                verification.deleted_bytes = double(receipt.deleted_bytes);
            end
        end

        function receipt = resumeReceipt(receiptPath, receipt, root, cfg, taskOptions)
            bms.data.StandardVerifiedSourceCsvCleanupService.assertBinding( ...
                receipt, receiptPath, root, cfg);
            if bms.data.VerifiedSourceCsvCleanupService. ...
                    hasCleanupAuthorization(receipt)
                expectedLockPath = ...
                    bms.data.StandardVerifiedSourceCsvCleanupService. ...
                        expectedCleanupLockPath(receipt, root);
                bms.data.VerifiedSourceCsvCleanupService. ...
                    assertCleanupAuthorization(receipt, receiptPath, ...
                        expectedLockPath, false);
            end
            if strcmp(char(string(receipt.status)), 'committed')
                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    assertCommitted(receipt, cfg);
                return;
            end
            options = bms.data.VerifiedSourceCsvCleanupService. ...
                optionsFromTask(taskOptions);
            if ~options.enabled
                error('BMS:CacheSourceCleanup:ResumeConfirmationRequired', ...
                    ['An interrupted destructive cleanup exists at %s. Re-run ' ...
                     'with the explicit cleanup confirmation to reconcile it.'], ...
                    receiptPath);
            end
            receipt = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                commitReceipt(receiptPath, receipt, cfg);
        end

        function rows = archivedRecords(root, startDate, endDate, cfg)
            days = bms.data.TimeRangeResolver.daysBetween(startDate, endDate);
            cells = {};
            for dayIndex = 1:numel(days)
                dayText = datestr(days(dayIndex), 'yyyy-mm-dd');
                receiptPath = bms.data.CacheSourceCleanupProvider. ...
                    standardReceiptPath(root, dayText);
                if ~isfile(receiptPath), continue; end
                receipt = bms.io.JsonFile.read(receiptPath);
                bms.data.StandardVerifiedSourceCsvCleanupService.assertBinding( ...
                    receipt, receiptPath, root, cfg);
                if bms.data.VerifiedSourceCsvCleanupService. ...
                        hasCleanupAuthorization(receipt)
                    expectedLockPath = ...
                        bms.data.StandardVerifiedSourceCsvCleanupService. ...
                            expectedCleanupLockPath(receipt, root);
                    bms.data.VerifiedSourceCsvCleanupService. ...
                        assertCleanupAuthorization(receipt, receiptPath, ...
                            expectedLockPath, false);
                end
                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    assertCommitted(receipt, cfg);
                for i = 1:numel(receipt.files)
                    entry = receipt.files(i);
                    cells{end+1} = struct( ... %#ok<AGROW>
                        'path', char(string(entry.source_path)), ...
                        'cache_path', char(string(entry.cache_path)), ...
                        'metadata_path', char(string(entry.metadata_path)), ...
                        'status', 'reused', ...
                        'source_bytes', double(entry.source_bytes), ...
                        'cache_bytes', double(entry.cache_bytes), ...
                        'modules', {{}}, 'point_ids', {{}}, ...
                        'sensor_types', {{}}, ...
                        'error_identifier', '', 'error_message', '', ...
                        'started_at', '', 'ended_at', '', 'elapsed_sec', 0);
                end
            end
            if isempty(cells), rows = struct([]); else, rows = [cells{:}]; end
        end

        function validateFreshDeletionEntry(receipt, entry, cfg)
            %VALIDATEFRESHDELETIONENTRY Explicit strong diagnostic verifier.
            %   Normal fresh commits use one immutable day authorization, not
            %   this per-file full cache/source revalidation helper.
            staged = char(string(entry.temporary_path));
            source = char(string(entry.source_path));
            if isfile(source) || ~isfile(staged)
                error('BMS:CacheSourceCleanup:DeleteStateInvalid', ...
                    'Fresh delete gate requires one staged CSV: %s', staged);
            end
            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                validateArchivedCache(entry, cfg);
            [~, proofEntry] = ...
                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    proofForSource(receipt.archive_proofs, entry.source_path);
            bms.data.ArchiveExtractService. ...
                verifyFileAgainstProofEntry(staged, proofEntry);
        end
    end

    methods (Static, Access = private)
        function entries = buildEntries(identities, proofs)
            entries = repmat(struct( ...
                'source_path', '', 'source_bytes', 0, ...
                'source_modified_at', '', 'source_crc32', 0, ...
                'source_modified_millis', 0, ...
                'cache_path', '', 'cache_modified_millis', 0, ...
                'metadata_path', '', 'metadata_bytes', 0, ...
                'metadata_modified_millis', 0, ...
                'pair_id', '', 'mat_bytes', 0, 'cache_bytes', 0, ...
                'sample_count', 0, 'proof_index', 0, ...
                'temporary_path', '', 'state', 'pending', ...
                'deleted_at', ''), 1, numel(identities));
            for i = 1:numel(identities)
                identity = identities(i);
                [proofIndex, proofEntry] = ...
                    bms.data.StandardVerifiedSourceCsvCleanupService. ...
                        proofForSource(proofs, identity.source_path);
                cacheInfo = dir(identity.cache_path);
                metadataInfo = dir(identity.metadata_path);
                if isempty(cacheInfo) || isempty(metadataInfo) ...
                        || double(cacheInfo(1).bytes) ~= double(identity.mat_bytes) ...
                        || double(cacheInfo(1).bytes) ...
                            + double(metadataInfo(1).bytes) ...
                            ~= double(identity.cache_bytes)
                    error('BMS:CacheSourceCleanup:CachePairChanged', ...
                        'Cache pair changed after preparation: %s', ...
                        identity.cache_path);
                end
                entries(i) = struct( ...
                    'source_path', identity.source_path, ...
                    'source_bytes', identity.source_bytes, ...
                    'source_modified_at', identity.source_modified_at, ...
                    'source_crc32', double(proofEntry.crc32), ...
                    'source_modified_millis', ...
                        bms.data.VerifiedSourceCsvCleanupService. ...
                            fileModifiedMillis(identity.source_path), ...
                    'cache_path', identity.cache_path, ...
                    'cache_modified_millis', ...
                        bms.data.VerifiedSourceCsvCleanupService. ...
                            fileModifiedMillis(identity.cache_path), ...
                    'metadata_path', identity.metadata_path, ...
                    'metadata_bytes', double(metadataInfo(1).bytes), ...
                    'metadata_modified_millis', ...
                        bms.data.VerifiedSourceCsvCleanupService. ...
                            fileModifiedMillis(identity.metadata_path), ...
                    'pair_id', identity.pair_id, ...
                    'mat_bytes', identity.mat_bytes, ...
                    'cache_bytes', identity.cache_bytes, ...
                    'sample_count', identity.sample_count, ...
                    'proof_index', proofIndex, ...
                    'temporary_path', '', ...
                    'state', 'pending', ...
                    'deleted_at', '');
            end
            [~, order] = sort(lower(string({entries.source_path})));
            entries = entries(order);
        end

        function receipt = commitReceipt(receiptPath, receipt, cfg, freshPrepared)
            if nargin < 4, freshPrepared = false; end
            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                assertReceiptShape(receipt, receiptPath);
            cleanupLockPath = ...
                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    dayLockPath(receipt.root, receipt.day);
            if freshPrepared
                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    assertFreshPreparedReceipt(receipt, receiptPath);
                if ~bms.data.VerifiedSourceCsvCleanupService. ...
                        hasCleanupAuthorization(receipt) ...
                        || ~isfield(receipt, 'cleanup_lock_path')
                    error('BMS:CacheSourceCleanup:AuthorizationBindingInvalid', ...
                        'Fresh cleanup requires an immutable day authorization.');
                end
                cleanupLockPath = ...
                    bms.data.StandardVerifiedSourceCsvCleanupService. ...
                        expectedCleanupLockPath(receipt, receipt.root);
                bms.data.VerifiedSourceCsvCleanupService. ...
                    assertCleanupAuthorization(receipt, receiptPath, ...
                        cleanupLockPath, true);
                receipt.commit_validation_mode = ...
                    'batch_authorized_fastpath';
            else
                if bms.data.VerifiedSourceCsvCleanupService. ...
                        hasCleanupAuthorization(receipt)
                    if ~isfield(receipt, 'cleanup_lock_path')
                        error('BMS:CacheSourceCleanup:AuthorizationBindingInvalid', ...
                            'Authorized cleanup receipt has no day-lock path.');
                    end
                    cleanupLockPath = ...
                        bms.data.StandardVerifiedSourceCsvCleanupService. ...
                            expectedCleanupLockPath(receipt, receipt.root);
                    bms.data.VerifiedSourceCsvCleanupService. ...
                        assertCleanupAuthorization(receipt, receiptPath, ...
                            cleanupLockPath, false);
                end
                receipt.commit_validation_mode = 'strict_recovery';
            end
            originalStatus = char(string(receipt.status));
            proofs = receipt.archive_proofs;
            for i = 1:numel(proofs)
                if ~bms.data.ArchiveExtractService. ...
                        verifyArchiveProof(proofs(i), ~freshPrepared)
                    error('BMS:CacheSourceCleanup:RecoveryArchiveChanged', ...
                        'Recovery ZIP changed before CSV deletion: %s', ...
                        char(string(proofs(i).archive_path)));
                end
            end
            entries = receipt.files;
            renamed = false(1, numel(entries));
            receipt.status = 'renaming';
            receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                publishReceipt(receiptPath, receipt);
            try
                for i = 1:numel(entries)
                    [~, proofEntry] = ...
                        bms.data.StandardVerifiedSourceCsvCleanupService. ...
                            proofForSource(proofs, entries(i).source_path);
                    source = char(string(entries(i).source_path));
                    staged = char(string(entries(i).temporary_path));
                    sourceExists = isfile(source);
                    stagedExists = isfile(staged);
                    if sourceExists && stagedExists
                        error('BMS:CacheSourceCleanup:DuplicatePendingSource', ...
                            'Both original and staged CSV exist: %s', source);
                    elseif sourceExists
                        if freshPrepared
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                assertFreshPreparedCache(entries(i));
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                assertFreshPreparedSource(entries(i), source);
                        else
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                validateEntryCache(entries(i), cfg);
                            bms.data.ArchiveExtractService. ...
                                verifyFileAgainstProofEntry(source, proofEntry);
                        end
                        [ok, message] = movefile(source, staged);
                        if ~ok
                            error('BMS:CacheSourceCleanup:StageRenameFailed', ...
                                'Unable to stage verified CSV: %s (%s)', ...
                                source, message);
                        end
                        renamed(i) = true;
                        entries(i).state = 'renamed';
                        if freshPrepared
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                assertFreshPreparedSource(entries(i), staged);
                        end
                    elseif stagedExists
                        % The process may stop after source->staging but before
                        % the next chunk receipt is durable. Re-prove actual
                        % staged bytes and reconcile from filesystem state.
                        if freshPrepared
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                assertFreshPreparedCache(entries(i));
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                assertFreshPreparedSource(entries(i), staged);
                        else
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                validateArchivedCache(entries(i), cfg);
                            bms.data.ArchiveExtractService. ...
                                verifyFileAgainstProofEntry(staged, proofEntry);
                        end
                        renamed(i) = true;
                        entries(i).state = 'renamed';
                    else
                        if ~ismember(originalStatus, ...
                                {'deleting','partial','committed'})
                            error( ...
                                'BMS:CacheSourceCleanup:SourceDisappearedBeforeDelete', ...
                                ['Neither original nor staged CSV exists before ' ...
                                 'a durable delete phase: %s'], source);
                        end
                        bms.data.StandardVerifiedSourceCsvCleanupService. ...
                            validateArchivedCache(entries(i), cfg);
                        entries(i).state = 'deleted_reconciled';
                        entries(i).deleted_at = datestr(datetime('now'), ...
                            'yyyy-mm-dd HH:MM:ss');
                    end
                    receipt.files = entries;
                    if bms.data.VerifiedSourceCsvCleanupService. ...
                            shouldCheckpointReceipt(i, numel(entries))
                        receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                            publishReceipt(receiptPath, receipt);
                    end
                end
            catch ME
                rollbackOk = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    rollbackRenamed(entries, renamed);
                if rollbackOk
                    receipt.status = 'rename_failed_rolled_back';
                    for j = find(renamed)
                        entries(j).state = 'pending';
                    end
                else
                    receipt.status = 'rename_failed_rollback_incomplete';
                end
                receipt.error_identifier = ME.identifier;
                receipt.error_message = ME.message;
                receipt.files = entries;
                receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                    publishReceipt(receiptPath, receipt);
                rethrow(ME);
            end

            % Crash recovery re-streams selected ZIP payloads. A fresh
            % transaction keeps the same live day lock and re-checks the
            % immutable authorization produced by its one deep pass once for
            % the whole natural-day batch, irrespective of ZIP group count.
            if freshPrepared
                bms.data.VerifiedSourceCsvCleanupService. ...
                    assertCleanupAuthorization(receipt, receiptPath, ...
                        cleanupLockPath, true);
                archiveVerified = true;
            else
                archiveVerified = true;
                for i = 1:numel(proofs)
                    archiveVerified = bms.data.ArchiveExtractService. ...
                        verifyArchiveProof(proofs(i), true) && archiveVerified;
                end
            end
            if ~archiveVerified
                rollbackOk = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    rollbackRenamed(entries, true(1, numel(entries)));
                if rollbackOk
                    for j = 1:numel(entries)
                        entries(j).state = 'pending';
                    end
                end
                receipt.status = ternary(rollbackOk, ...
                    'recovery_changed_rolled_back', ...
                    'recovery_changed_rollback_incomplete');
                receipt.error_identifier = ...
                    'BMS:CacheSourceCleanup:RecoveryArchiveChanged';
                receipt.error_message = ...
                    'Recovery ZIP changed after CSV staging.';
                receipt.files = entries;
                receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                    publishReceipt(receiptPath, receipt);
                error(receipt.error_identifier, '%s', receipt.error_message);
            end

            receipt.status = 'deleting';
            receipt.files = entries;
            if freshPrepared
                bms.data.VerifiedSourceCsvCleanupService. ...
                    assertCleanupAuthorization(receipt, receiptPath, ...
                        cleanupLockPath, true);
            end
            receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                publishReceipt(receiptPath, receipt);
            try
                for i = 1:numel(entries)
                    staged = char(string(entries(i).temporary_path));
                    source = char(string(entries(i).source_path));
                    state = char(string(entries(i).state));
                    sourceExists = isfile(source);
                    stagedExists = isfile(staged);
                    if sourceExists
                        error('BMS:CacheSourceCleanup:DeleteStateInvalid', ...
                            'Original CSV exists at the delete boundary: %s', source);
                    end
                    if freshPrepared
                        bms.data.StandardVerifiedSourceCsvCleanupService. ...
                            assertFreshPreparedCache(entries(i));
                        if stagedExists
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                assertFreshPreparedSource(entries(i), staged);
                        end
                    else
                        bms.data.StandardVerifiedSourceCsvCleanupService. ...
                            validateArchivedCache(entries(i), cfg);
                    end
                    if ismember(state, {'deleted','deleted_reconciled'})
                        if stagedExists
                            error('BMS:CacheSourceCleanup:DeleteStateInvalid', ...
                                ['Receipt says deleted but staging still exists: ' ...
                                 '%s'], staged);
                        end
                        continue;
                    end
                    if strcmp(state, 'renamed') && stagedExists
                        [~, proofEntry] = ...
                            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                proofForSource(proofs, entries(i).source_path);
                        if ~freshPrepared
                            bms.data.ArchiveExtractService. ...
                                verifyFileAgainstProofEntry(staged, proofEntry);
                        end
                        delete(staged);
                        if isfile(source) || isfile(staged)
                            error('BMS:CacheSourceCleanup:DeleteFailed', ...
                                'CSV still exists after deletion attempt: %s', source);
                        end
                        entries(i).state = 'deleted';
                        entries(i).deleted_at = datestr(datetime('now'), ...
                            'yyyy-mm-dd HH:MM:ss');
                    elseif strcmp(state, 'renamed') && ~stagedExists ...
                            && ismember(originalStatus, ...
                                {'deleting','partial','committed'})
                        entries(i).state = 'deleted_reconciled';
                        entries(i).deleted_at = datestr(datetime('now'), ...
                            'yyyy-mm-dd HH:MM:ss');
                    else
                        error('BMS:CacheSourceCleanup:DeleteStateInvalid', ...
                            'Staged CSV state is invalid: %s', staged);
                    end
                    receipt.files = entries;
                    receipt.deleted_count = nnz(ismember( ...
                        cellstr(string({entries.state})), ...
                        {'deleted','deleted_reconciled'}));
                    receipt.deleted_bytes = sum(double([entries(ismember( ...
                        cellstr(string({entries.state})), ...
                        {'deleted','deleted_reconciled'})).source_bytes]));
                    if bms.data.VerifiedSourceCsvCleanupService. ...
                            shouldCheckpointReceipt(i, numel(entries))
                        receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                            publishReceipt(receiptPath, receipt);
                    end
                end
            catch ME
                receipt.status = 'partial';
                receipt.error_identifier = ME.identifier;
                receipt.error_message = ME.message;
                receipt.files = entries;
                receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                    publishReceipt(receiptPath, receipt);
                rethrow(ME);
            end
            receipt.status = 'committed';
            receipt.committed_at = datestr(datetime('now'), ...
                'yyyy-mm-dd HH:MM:ss');
            receipt.error_identifier = '';
            receipt.error_message = '';
            receipt.deleted_count = numel(entries);
            receipt.deleted_bytes = sum(double([entries.source_bytes]));
            receipt.files = entries;
            receipt = bms.data.VerifiedSourceCsvCleanupService. ...
                publishReceipt(receiptPath, receipt);
        end

        function assertFreshPreparedReceipt(receipt, receiptPath)
            states = cellstr(string({receipt.files.state}));
            required = {'source_modified_millis','cache_modified_millis', ...
                'metadata_bytes','metadata_modified_millis'};
            valid = strcmp(char(string(receipt.status)), 'prepared') ...
                && ~isempty(receipt.files) && all(strcmp(states, 'pending'));
            for i = 1:numel(receipt.files)
                valid = valid && all(isfield(receipt.files(i), required));
            end
            if ~valid
                error('BMS:CacheSourceCleanup:FreshPreparationInvalid', ...
                    ['Fresh validation reuse is permitted only for the newly ' ...
                     'prepared in-process receipt: %s'], receiptPath);
            end
        end

        function assertFreshPreparedSource(entry, actualPath)
            bms.data.VerifiedSourceCsvCleanupService. ...
                assertFreshFileFingerprint(actualPath, entry.source_bytes, ...
                    entry.source_modified_millis, ...
                    'BMS:CacheSourceCleanup:SourceChanged');
        end

        function assertFreshPreparedCache(entry)
            bms.data.VerifiedSourceCsvCleanupService. ...
                assertFreshFileFingerprint(entry.cache_path, entry.mat_bytes, ...
                    entry.cache_modified_millis, ...
                    'BMS:CacheSourceCleanup:CachePairChanged');
            bms.data.VerifiedSourceCsvCleanupService. ...
                assertFreshFileFingerprint(entry.metadata_path, ...
                    entry.metadata_bytes, entry.metadata_modified_millis, ...
                    'BMS:CacheSourceCleanup:CachePairChanged');
        end

        function validateEntryCache(entry, cfg)
            identity = bms.data.CacheSourceCleanupProvider. ...
                validateStandardCache(entry.source_path, entry.cache_path, cfg);
            fields = {'source_bytes','source_modified_at','metadata_path', ...
                'pair_id','mat_bytes','cache_bytes','sample_count'};
            for i = 1:numel(fields)
                name = fields{i};
                expected = entry.(name);
                actual = identity.(name);
                if isnumeric(expected)
                    matches = double(expected) == double(actual);
                else
                    matches = strcmpi(char(string(expected)), char(string(actual)));
                end
                if ~matches
                    error('BMS:CacheSourceCleanup:CachePairChanged', ...
                        'Cache identity changed during cleanup: %s', entry.cache_path);
                end
            end
        end

        function assertBinding(receipt, receiptPath, root, cfg)
            bms.data.StandardVerifiedSourceCsvCleanupService. ...
                assertReceiptShape(receipt, receiptPath);
            provider = bms.data.CacheSourceCleanupProvider.resolve(root, cfg);
            expectedScope = bms.data.CacheSourceCleanupProvider. ...
                standardScopeHash(cfg, provider.layout, provider.cache_version);
            expectedPath = bms.data.CacheSourceCleanupProvider. ...
                standardReceiptPath(root, receipt.day);
            if ~strcmp(receipt.provider_id, 'standard_timeseries_v1') ...
                    || ~strcmp(receipt.layout, provider.layout) ...
                    || ~strcmp(receipt.cache_version, provider.cache_version) ...
                    || ~strcmp(receipt.scope_hash, expectedScope) ...
                    || ~strcmpi( ...
                        bms.data.CacheSourceCleanupProvider.canonicalPath(receipt.root), ...
                        bms.data.CacheSourceCleanupProvider.canonicalPath(root)) ...
                    || ~strcmpi( ...
                        bms.data.CacheSourceCleanupProvider.canonicalPath(receiptPath), ...
                        bms.data.CacheSourceCleanupProvider.canonicalPath(expectedPath))
                error('BMS:CacheSourceCleanup:ReceiptBindingMismatch', ...
                    'Standard cleanup receipt does not match the active task: %s', ...
                    receiptPath);
            end
        end

        function assertReceiptShape(receipt, receiptPath)
            required = {'schema_version','receipt_type','provider_id', ...
                'receipt_id','status','mode','commit_scope','recovery_policy', ...
                'confirmation','confirmed_at','root','day','layout', ...
                'cache_version','scope_hash','archive_proofs','files'};
            if ~isstruct(receipt) || ~isscalar(receipt) ...
                    || ~all(isfield(receipt, required)) ...
                    || double(receipt.schema_version) ~= 3 ...
                    || ~strcmp(char(string(receipt.receipt_type)), ...
                        'verified_cache_source_cleanup') ...
                    || ~strcmp(char(string(receipt.mode)), ...
                        'verified_extracted_csv') ...
                    || ~strcmp(char(string(receipt.commit_scope)), 'day') ...
                    || ~strcmp(char(string(receipt.recovery_policy)), ...
                        'verified_archive') ...
                    || ~strcmp(char(string(receipt.confirmation)), ...
                        'DELETE_VERIFIED_EXTRACTED_CSV') ...
                    || isempty(strtrim(char(string(receipt.confirmed_at)))) ...
                    || isempty(receipt.files) || isempty(receipt.archive_proofs)
                error('BMS:CacheSourceCleanup:ReceiptBindingMismatch', ...
                    'Standard cleanup receipt is malformed or unsafe: %s', receiptPath);
            end
            for i = 1:numel(receipt.files)
                entry = receipt.files(i);
                entryRequired = {'source_path','source_bytes', ...
                    'source_modified_at','source_crc32','cache_path', ...
                    'metadata_path','pair_id','mat_bytes','cache_bytes', ...
                    'sample_count','proof_index','temporary_path','state', ...
                    'deleted_at'};
                if ~isstruct(entry) || ~isscalar(entry) ...
                        || ~all(isfield(entry, entryRequired)) ...
                        || isempty(char(string(entry.source_path))) ...
                        || isempty(char(string(entry.cache_path))) ...
                        || isempty(char(string(entry.metadata_path))) ...
                        || isempty(char(string(entry.pair_id))) ...
                        || isempty(char(string(entry.temporary_path))) ...
                        || ~bms.data.CacheSourceCleanupProvider.isPathInside( ...
                        entry.source_path, receipt.root) ...
                        || ~bms.data.CacheSourceCleanupProvider.isPathInside( ...
                            entry.cache_path, receipt.root) ...
                        || ~bms.data.CacheSourceCleanupProvider.isPathInside( ...
                            entry.metadata_path, receipt.root) ...
                        || ~bms.data.CacheSourceCleanupProvider.isPathInside( ...
                            entry.temporary_path, fileparts(entry.source_path)) ...
                        || ~strcmpi( ...
                            bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                                entry.cache_path), ...
                            bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                                bms.data.CacheSourceCleanupProvider. ...
                                    expectedCachePath(entry.source_path, ...
                                    struct('id','standard_timeseries_v1')))) ...
                        || ~strcmpi( ...
                            bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                                entry.metadata_path), ...
                            bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                                bms.data.CacheManager.metadataPath( ...
                                    entry.cache_path))) ...
                        || ~strcmpi( ...
                            bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                                entry.temporary_path), ...
                            bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                                    expectedTemporary(entry, receipt.receipt_id)))
                    error('BMS:CacheSourceCleanup:UnsafeReceiptPath', ...
                        'Standard cleanup receipt contains an unsafe path: %s', ...
                        receiptPath);
                end
                proofIndex = double(entry.proof_index);
                if ~isscalar(proofIndex) || ~isfinite(proofIndex) ...
                        || proofIndex ~= floor(proofIndex) || proofIndex < 1 ...
                        || proofIndex > numel(receipt.archive_proofs)
                    error('BMS:CacheSourceCleanup:ReceiptBindingMismatch', ...
                        'Standard cleanup receipt has an invalid archive proof index: %s', ...
                        receiptPath);
                end
                [actualProofIndex, proofEntry] = ...
                    bms.data.StandardVerifiedSourceCsvCleanupService. ...
                        proofForSource(receipt.archive_proofs, entry.source_path);
                if proofIndex ~= actualProofIndex ...
                        || double(entry.source_bytes) ~= double(proofEntry.bytes) ...
                        || double(entry.source_crc32) ~= double(proofEntry.crc32)
                    error('BMS:CacheSourceCleanup:ReceiptBindingMismatch', ...
                        ['Standard cleanup receipt source/proof identity does ' ...
                         'not close: %s'], receiptPath);
                end
            end
        end

        function assertCommitted(receipt, cfg)
            states = cellstr(string({receipt.files.state}));
            if ~strcmp(char(string(receipt.status)), 'committed') ...
                    || isempty(strtrim(char(string(receipt.committed_at)))) ...
                    || double(receipt.deleted_count) ~= numel(receipt.files) ...
                    || double(receipt.deleted_bytes) ...
                        ~= sum(double([receipt.files.source_bytes])) ...
                    || ~all(ismember(states, {'deleted','deleted_reconciled'}))
                error('BMS:CacheSourceCleanup:CommittedReceiptInvalid', ...
                    'Committed standard cleanup receipt counters do not close.');
            end
            for i = 1:numel(receipt.archive_proofs)
                if ~bms.data.ArchiveExtractService. ...
                        verifyArchiveProof(receipt.archive_proofs(i))
                    error('BMS:CacheSourceCleanup:RecoveryArchiveChanged', ...
                        'Recovery ZIP changed after CSV cleanup.');
                end
            end
            for i = 1:numel(receipt.files)
                entry = receipt.files(i);
                if isfile(entry.source_path) || isfile(entry.temporary_path)
                    error('BMS:CacheSourceCleanup:CommittedSourceStateInvalid', ...
                        'Committed cleanup still has source/staging CSV: %s', ...
                        entry.source_path);
                end
                % Source is deliberately absent, so validate the cache pair
                % against the immutable receipt rather than rebuilding the
                % live source record.
                bms.data.StandardVerifiedSourceCsvCleanupService. ...
                    validateArchivedCache(entry, cfg);
            end
        end

        function validateArchivedCache(entry, cfg)
            cachePath = char(string(entry.cache_path));
            metaPath = char(string(entry.metadata_path));
            version = bms.data.TimeSeriesLoader.seriesCacheVersion(cfg);
            if ~isfile(cachePath) || ~isfile(metaPath) ...
                    || ~bms.data.CacheManager.metadataMatches( ...
                        cachePath, struct(), version) ...
                    || ~bms.data.CacheManager.cachePairIntegrityMatches(cachePath)
                error('BMS:CacheSourceCleanup:ArchivedCacheInvalid', ...
                    'Archived-source cache pair is invalid: %s', cachePath);
            end
            meta = bms.io.JsonFile.read(metaPath);
            sourceRecords = bms.data.CacheManager.normalizeSourceRecords( ...
                meta.source_records);
            info = dir(cachePath);
            if numel(sourceRecords) ~= 1 ...
                    || ~strcmpi( ...
                        bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                            sourceRecords(1).path), ...
                        bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                            entry.source_path)) ...
                    || double(sourceRecords(1).bytes) ~= double(entry.source_bytes) ...
                    || ~logical(sourceRecords(1).exists) ...
                    || ~strcmp(sourceRecords(1).modified_at, ...
                        entry.source_modified_at) ...
                    || ~strcmp(char(string(meta.pair_id)), entry.pair_id) ...
                    || double(meta.mat_bytes) ~= double(entry.mat_bytes) ...
                    || isempty(info) || double(info(1).bytes) ~= double(entry.mat_bytes) ...
                    || bms.data.StandardVerifiedSourceCsvCleanupService. ...
                        cachePairBytes(cachePath) ~= double(entry.cache_bytes)
                error('BMS:CacheSourceCleanup:ArchivedCacheInvalid', ...
                    'Archived-source cache identity changed: %s', cachePath);
            end
            opts = struct('cache_version', version, 'require_metadata', true);
            [times, vals, loaded] = bms.data.TimeSeriesLoader.readMatSeries( ...
                cachePath, opts);
            if ~logical(loaded.read_ok) || isempty(times) ...
                    || numel(times) ~= numel(vals) ...
                    || numel(vals) ~= double(entry.sample_count)
                error('BMS:CacheSourceCleanup:ArchivedCacheInvalid', ...
                    'Archived-source cache failed standalone load: %s', cachePath);
            end
        end

        function [proofIndex, entry] = proofForSource(proofs, sourcePath)
            matches = [];
            entry = struct();
            for i = 1:numel(proofs)
                paths = cellstr(string({proofs(i).files.path}));
                indexes = find(strcmpi(paths, char(string(sourcePath))));
                if numel(indexes) == 1
                    matches(end+1) = i; %#ok<AGROW>
                    entry = proofs(i).files(indexes);
                end
            end
            if numel(matches) ~= 1
                error('BMS:CacheSourceCleanup:RecoveryArchiveAmbiguous', ...
                    'Cleanup source is not bound to exactly one archive proof: %s', ...
                    sourcePath);
            end
            proofIndex = matches(1);
        end

        function pathValue = expectedTemporary(entry, receiptId)
            [folder, base, ext] = fileparts(char(string(entry.source_path)));
            pathValue = fullfile(folder, sprintf('.%s%s.bmsdelete.%s', ...
                base, ext, char(string(receiptId))));
        end

        function ok = rollbackRenamed(entries, renamed)
            ok = true;
            for i = find(renamed)
                source = char(string(entries(i).source_path));
                staged = char(string(entries(i).temporary_path));
                if isfile(staged) && ~isfile(source)
                    [moved, ~] = movefile(staged, source);
                    ok = ok && moved;
                elseif isfile(staged) || ~isfile(source)
                    ok = false;
                end
            end
            % A pre-existing staged file can fail validation before it is
            % added to RENAMED. Do not report a successful rollback unless
            % every entry is actually restored to source-only state.
            for i = 1:numel(entries)
                source = char(string(entries(i).source_path));
                staged = char(string(entries(i).temporary_path));
                if ~isfile(source) || isfile(staged)
                    ok = false;
                end
            end
        end

        function cleanup = acquireDayLease(root, day)
            cleanup = bms.data.DailyExportMutationLock.acquire(root, day);
        end

        function lockPath = dayLockPath(root, day)
            lockPath = bms.data.DailyExportMutationLock.pathFor(root, day);
        end

        function lockPath = expectedCleanupLockPath(receipt, trustedRoot)
            if ~isfield(receipt, 'cleanup_lock_path')
                error('BMS:CacheSourceCleanup:AuthorizationBindingInvalid', ...
                    'Authorized cleanup receipt has no day-lock path.');
            end
            lockPath = bms.data.StandardVerifiedSourceCsvCleanupService. ...
                dayLockPath(trustedRoot, receipt.day);
            if ~strcmpi( ...
                    bms.data.CacheSourceCleanupProvider.canonicalPath( ...
                        receipt.cleanup_lock_path), ...
                    bms.data.CacheSourceCleanupProvider.canonicalPath(lockPath))
                error('BMS:CacheSourceCleanup:AuthorizationLockMismatch', ...
                    'Standard cleanup receipt is bound to a different day lock.');
            end
        end

        function bytes = cachePairBytes(cachePath)
            bytes = 0;
            paths = {char(string(cachePath)), ...
                bms.data.CacheManager.metadataPath(cachePath)};
            for i = 1:numel(paths)
                info = dir(paths{i});
                if ~isempty(info), bytes = bytes + double(info(1).bytes); end
            end
        end
    end
end

function out = ternary(condition, yesValue, noValue)
if condition
    out = yesValue;
else
    out = noValue;
end
end
