classdef VerifiedSourceCsvCleanupService
    %VERIFIEDSOURCECSVCLEANUPSERVICE Safely archive extracted CSV after caching.
    %   Destructive cleanup is task-scoped, disabled by default, and limited
    %   to verified daily-export partitions. Cache workers never delete source
    %   files; the parent process commits one day at a time and writes a
    %   durable receipt that supports cache-only discovery and crash recovery.

    methods (Static)
        function options = optionsFromTask(taskOptions)
            options = struct( ...
                'enabled', false, ...
                'mode', 'verified_extracted_csv', ...
                'commit_scope', 'day', ...
                'recovery_policy', 'verified_archive', ...
                'confirmation', '', ...
                'confirmed_at', '');
            if nargin < 1 || isempty(taskOptions), return; end
            if ~isstruct(taskOptions) || ~isscalar(taskOptions)
                error('BMS:CacheSourceCleanup:InvalidTaskOptions', ...
                    'Task options must be a scalar struct.');
            end
            if ~isfield(taskOptions, 'cache_source_cleanup') ...
                    || isempty(taskOptions.cache_source_cleanup)
                return;
            end
            section = taskOptions.cache_source_cleanup;
            if ~isstruct(section) || ~isscalar(section)
                error('BMS:CacheSourceCleanup:InvalidOptions', ...
                    'options.cache_source_cleanup must be a scalar object.');
            end
            allowed = fieldnames(options);
            unknown = setdiff(fieldnames(section), allowed, 'stable');
            if ~isempty(unknown)
                error('BMS:CacheSourceCleanup:UnknownOption', ...
                    'Unknown cache_source_cleanup option(s): %s', strjoin(unknown, ', '));
            end
            for i = 1:numel(allowed)
                name = allowed{i};
                if isfield(section, name) && ~isempty(section.(name))
                    options.(name) = section.(name);
                end
            end
            if ~(islogical(options.enabled) || isnumeric(options.enabled)) ...
                    || ~isscalar(options.enabled) || ~isfinite(double(options.enabled)) ...
                    || ~ismember(double(options.enabled), [0 1])
                error('BMS:CacheSourceCleanup:InvalidEnabledFlag', ...
                    'cache_source_cleanup.enabled must be one boolean value.');
            end
            options.enabled = logical(options.enabled);
            options.mode = lower(strtrim(char(string(options.mode))));
            options.commit_scope = lower(strtrim(char(string(options.commit_scope))));
            options.recovery_policy = lower(strtrim(char(string(options.recovery_policy))));
            options.confirmation = char(string(options.confirmation));
            options.confirmed_at = char(string(options.confirmed_at));
            if ~options.enabled, return; end
            if ~strcmp(options.mode, 'verified_extracted_csv') ...
                    || ~strcmp(options.commit_scope, 'day') ...
                    || ~strcmp(options.recovery_policy, 'verified_archive')
                error('BMS:CacheSourceCleanup:UnsafePolicy', ...
                    ['CSV cleanup requires mode=verified_extracted_csv, ' ...
                     'commit_scope=day and recovery_policy=verified_archive.']);
            end
            if ~strcmp(options.confirmation, 'DELETE_VERIFIED_EXTRACTED_CSV')
                error('BMS:CacheSourceCleanup:ConfirmationRequired', ...
                    ['Destructive CSV cleanup was requested without the exact ' ...
                     'DELETE_VERIFIED_EXTRACTED_CSV confirmation token.']);
            end
            if isempty(strtrim(options.confirmed_at))
                error('BMS:CacheSourceCleanup:ConfirmationTimeRequired', ...
                    'Destructive CSV cleanup requires a non-empty confirmation timestamp.');
            end
            enabledModules = bms.module.ModuleRegistry.enabledFromOptions(taskOptions);
            allowedModules = {'zip_precheck','unzip','cache_prebuild'};
            unsafe = enabledModules(~ismember({enabledModules.Key}, allowedModules));
            if ~isempty(unsafe)
                error('BMS:CacheSourceCleanup:DedicatedTaskRequired', ...
                    ['Verified CSV cleanup must run as a dedicated preprocessing task. ' ...
                     'Remove these later/mutating modules and run analysis from MAT in a ' ...
                     'separate task: %s'], strjoin({unsafe.Label}, ', '));
            end
        end

        function tf = isEnabled(taskOptions)
            tf = bms.data.VerifiedSourceCsvCleanupService.optionsFromTask(taskOptions).enabled;
        end

        function path = receiptPath(partitionRoot)
            path = fullfile(char(string(partitionRoot)), ...
                '.bms_cache_source_cleanup_receipt.json');
        end

        function root = partitionRoot(csvDir)
            root = char(string(csvDir));
            for i = 1:12
                if isfile(fullfile(root, '.bms_extract_manifest.json'))
                    return;
                end
                parent = fileparts(root);
                if isempty(parent) || strcmp(parent, root), break; end
                root = parent;
            end
            error('BMS:CacheSourceCleanup:ExtractionManifestMissing', ...
                'No verified daily extraction manifest is an ancestor of: %s', csvDir);
        end

        function resumePending(csvDirs, cfg, taskOptions, cacheVersion, configHash)
            if nargin < 3, taskOptions = struct(); end
            if nargin < 4, cacheVersion = 'jlj_csv_v2'; end
            if nargin < 5, configHash = ''; end
            csvDirs = unique(cellstr(string(csvDirs)), 'stable');
            roots = {};
            for i = 1:numel(csvDirs)
                try
                    roots{end+1} = bms.data.VerifiedSourceCsvCleanupService.partitionRoot( ...
                        csvDirs{i}); %#ok<AGROW>
                catch
                    orphanReceipt = ...
                        bms.data.VerifiedSourceCsvCleanupService.findReceiptAncestor( ...
                        csvDirs{i});
                    if ~isempty(orphanReceipt)
                        error('BMS:CacheSourceCleanup:ExtractionManifestLost', ...
                            ['A cleanup receipt exists but its verified extraction manifest ' ...
                             'is missing: %s'], orphanReceipt);
                    end
                end
            end
            roots = unique(roots, 'stable');
            for i = 1:numel(roots)
                lease = bms.data.VerifiedSourceCsvCleanupService. ...
                    acquirePartitionLease(roots{i}); %#ok<NASGU>
                receiptPath = bms.data.VerifiedSourceCsvCleanupService.receiptPath(roots{i});
                if ~isfile(receiptPath), continue; end
                receipt = bms.io.JsonFile.read(receiptPath);
                if strcmp(char(string(receipt.status)), 'committed'), continue; end
                options = bms.data.VerifiedSourceCsvCleanupService.optionsFromTask(taskOptions);
                if ~options.enabled
                    error('BMS:CacheSourceCleanup:ResumeConfirmationRequired', ...
                        ['An interrupted destructive cleanup exists at %s. Re-run with ' ...
                         'the explicit cleanup confirmation to reconcile it.'], receiptPath);
                end
                bms.data.VerifiedSourceCsvCleanupService.resumeReceipt( ...
                    receiptPath, receipt, cfg, cacheVersion, configHash);
            end
        end

        function verification = reconcilePendingDay(root, day, cfg, taskOptions)
            %RECONCILEPENDINGDAY Finish an interrupted daily cleanup before unzip.
            %   This deliberately keeps mutation out of verifyCommittedDay.
            %   A daily streaming restart first reconciles a prepared/partial
            %   receipt under the original explicit task confirmation, then
            %   proves the resulting committed day can safely skip extraction.
            if nargin < 3, cfg = struct(); end
            if nargin < 4, taskOptions = struct(); end
            dayText = bms.data.TimeRangeResolver.toDateString(day);
            csvDirs = bms.data.ZipDailyExportAdapter.csvDirs( ...
                root, dayText, dayText, cfg);
            adapter = bms.data.JiulongjiangCsvDataSource.adapterFromConfig(cfg);
            cacheVersion = 'jlj_csv_v2';
            configHash = bms.data.CacheManager.configHash(adapter);
            bms.data.VerifiedSourceCsvCleanupService.resumePending( ...
                csvDirs, cfg, taskOptions, cacheVersion, configHash);
            verification = bms.data.VerifiedSourceCsvCleanupService. ...
                verifyCommittedDay(root, dayText, cfg);
        end

        function discovery = archivedDiscovery(csvDirs, cfg, cacheVersion, configHash)
            %ARCHIVEDDISCOVERY Enumerate only caches authorised by receipts.
            if nargin < 3, cacheVersion = 'jlj_csv_v2'; end
            if nargin < 4, configHash = ''; end
            rows = {};
            csvDirs = unique(cellstr(string(csvDirs)), 'stable');
            for i = 1:numel(csvDirs)
                try
                    partitionRoot = bms.data.VerifiedSourceCsvCleanupService.partitionRoot( ...
                        csvDirs{i});
                catch
                    orphanReceipt = ...
                        bms.data.VerifiedSourceCsvCleanupService.findReceiptAncestor( ...
                        csvDirs{i});
                    if ~isempty(orphanReceipt)
                        error('BMS:CacheSourceCleanup:ExtractionManifestLost', ...
                            ['Archived cache discovery found a cleanup receipt without its ' ...
                             'verified extraction manifest: %s'], orphanReceipt);
                    end
                    continue;
                end
                receiptPath = bms.data.VerifiedSourceCsvCleanupService.receiptPath(partitionRoot);
                if ~isfile(receiptPath), continue; end
                receipt = bms.io.JsonFile.read(receiptPath);
                bms.data.VerifiedSourceCsvCleanupService.assertReceiptBinding( ...
                    receipt, cacheVersion, configHash, receiptPath, cfg);
                if ~strcmp(char(string(receipt.status)), 'committed')
                    error('BMS:CacheSourceCleanup:ReceiptIncomplete', ...
                        'Cleanup receipt is not committed: %s', receiptPath);
                end
                bms.data.VerifiedSourceCsvCleanupService.assertCommittedReceiptState( ...
                    receipt, receiptPath);
                if ~bms.data.ArchiveExtractService.verifyArchiveProof(receipt.archive_proof)
                    error('BMS:CacheSourceCleanup:RecoveryArchiveChanged', ...
                        'Recovery ZIP changed after CSV cleanup: %s', receiptPath);
                end
                entries = receipt.files;
                if isempty(entries), continue; end
                for j = 1:numel(entries)
                    bms.data.VerifiedSourceCsvCleanupService.assertCacheEntry( ...
                        receipt, entries(j), cfg);
                    source = char(string(entries(j).source_path));
                    temp = char(string(entries(j).temporary_path));
                    if isfile(source)
                        continue;
                    end
                    if isfile(temp)
                        error('BMS:CacheSourceCleanup:TemporarySourceRemains', ...
                            'Pending-delete CSV remains after a committed receipt: %s', temp);
                    end
                    cachePath = char(string(entries(j).cache_path));
                    if ~bms.data.JiulongjiangCsvDataSource.validateStandaloneRawCache( ...
                            cachePath, cfg)
                        error('BMS:CacheSourceCleanup:ArchivedCacheInvalid', ...
                            'Archived CSV cache is no longer independently valid: %s', cachePath);
                    end
                    rows{end+1} = struct( ... %#ok<AGROW>
                        'path', source, ...
                        'source_bytes', double(entries(j).source_bytes), ...
                        'source_modified_at', char(string(entries(j).source_modified_at)), ...
                        'header', {{}}, ...
                        'classification', 'eligible', ...
                        'reason', 'verified_source_archived', ...
                        'error_identifier', '', ...
                        'error_message', '', ...
                        'source_present', false, ...
                        'cache_path', cachePath, ...
                        'metadata_path', char(string(entries(j).metadata_path)), ...
                        'cleanup_receipt_path', receiptPath, ...
                        'csv_dir', char(string(csvDirs{i})), ...
                        'partition_root', partitionRoot);
                end
            end
            if isempty(rows), discovery = struct([]); else, discovery = [rows{:}]; end
        end

        function verification = verifyCommittedDay(root, day, cfg)
            %VERIFYCOMMITTEDDAY Prove one previously cleaned day is reusable.
            %   A new streaming session must not attempt to re-extract a day
            %   whose eligible CSV files were deliberately removed.  This
            %   method only authorises that skip after the receipt, recovery
            %   ZIP, cache pairs and the absent source/staging state all close.
            if nargin < 3, cfg = struct(); end
            dayText = bms.data.TimeRangeResolver.toDateString(day);
            verification = struct('committed', false, 'day', dayText, ...
                'receipt_path', '', 'cache_count', 0, ...
                'deleted_count', 0, 'deleted_bytes', 0);
            csvDirs = bms.data.ZipDailyExportAdapter.csvDirs( ...
                root, dayText, dayText, cfg);
            if isempty(csvDirs), return; end
            adapter = bms.data.JiulongjiangCsvDataSource.adapterFromConfig(cfg);
            cacheVersion = 'jlj_csv_v2';
            configHash = bms.data.CacheManager.configHash(adapter);
            matched = {};
            for i = 1:numel(csvDirs)
                partitionRoot = ...
                    bms.data.VerifiedSourceCsvCleanupService.partitionRoot(csvDirs{i});
                receiptPath = ...
                    bms.data.VerifiedSourceCsvCleanupService.receiptPath(partitionRoot);
                if isfile(receiptPath)
                    matched{end+1} = struct('csv_dir', csvDirs{i}, ... %#ok<AGROW>
                        'partition_root', partitionRoot, ...
                        'receipt_path', receiptPath);
                end
            end
            if isempty(matched), return; end
            if numel(matched) ~= 1
                error('BMS:CacheSourceCleanup:CommittedDayAmbiguous', ...
                    'Expected exactly one cleanup receipt for %s.', dayText);
            end
            match = matched{1};
            receipt = bms.io.JsonFile.read(match.receipt_path);
            bms.data.VerifiedSourceCsvCleanupService.assertReceiptBinding( ...
                receipt, cacheVersion, configHash, match.receipt_path, cfg);
            if ~strcmp(char(string(receipt.status)), 'committed')
                error('BMS:CacheSourceCleanup:ReceiptIncomplete', ...
                    'Cleanup receipt is not committed: %s', match.receipt_path);
            end
            bms.data.VerifiedSourceCsvCleanupService.assertCommittedReceiptState( ...
                receipt, match.receipt_path);
            if ~strcmp(char(string(receipt.day)), dayText) ...
                    || ~bms.data.VerifiedSourceCsvCleanupService.isPathInside( ...
                        match.partition_root, root)
                error('BMS:CacheSourceCleanup:ReceiptDayMismatch', ...
                    'Cleanup receipt is not bound to requested day/root: %s', ...
                    match.receipt_path);
            end
            if ~bms.data.ArchiveExtractService.verifyArchiveProof(receipt.archive_proof)
                error('BMS:CacheSourceCleanup:RecoveryArchiveChanged', ...
                    'Recovery ZIP changed after CSV cleanup: %s', match.receipt_path);
            end
            entries = receipt.files;
            if isempty(entries)
                error('BMS:CacheSourceCleanup:ReceiptEmpty', ...
                    'Committed cleanup receipt has no cache entries: %s', ...
                    match.receipt_path);
            end
            for i = 1:numel(entries)
                source = char(string(entries(i).source_path));
                temp = char(string(entries(i).temporary_path));
                if isfile(source) || isfile(temp)
                    error('BMS:CacheSourceCleanup:CommittedSourceStateInvalid', ...
                        ['Committed cleanup receipt still has a source or staged CSV; ' ...
                         'refusing to skip extraction: %s'], source);
                end
                bms.data.VerifiedSourceCsvCleanupService.assertCacheEntry( ...
                    receipt, entries(i), cfg);
            end
            verification.committed = true;
            verification.receipt_path = match.receipt_path;
            verification.cache_count = numel(entries);
            verification.deleted_count = double(receipt.deleted_count);
            verification.deleted_bytes = double(receipt.deleted_bytes);
        end

        function result = commitJljPartition(root, day, csvDir, records, cfg, ...
                taskOptions, cacheVersion, configHash)
            options = bms.data.VerifiedSourceCsvCleanupService.optionsFromTask(taskOptions);
            result = struct('enabled', options.enabled, 'status', 'retained', ...
                'day', char(string(day)), 'receipt_path', '', ...
                'deleted_count', 0, 'deleted_bytes', 0);
            if ~options.enabled, return; end
            if nargin < 7 || isempty(cacheVersion), cacheVersion = 'jlj_csv_v2'; end
            if nargin < 8, configHash = ''; end
            if isempty(records)
                error('BMS:CacheSourceCleanup:NoEligibleRecords', ...
                    'No eligible cache records exist for %s.', char(string(day)));
            end
            % Keep the public commit API fail-safe as well as its current
            % callers.  The common day mutation lock serialises extraction,
            % cache generation and cleanup; acquisition precedes the narrower
            % partition lease to preserve the global lock order.
            dayMutationLease = bms.data.DailyExportMutationLock.acquire( ...
                root, char(string(day))); %#ok<NASGU>
            partitionRoot = bms.data.VerifiedSourceCsvCleanupService.partitionRoot(csvDir);
            partitionLease = bms.data.VerifiedSourceCsvCleanupService. ...
                acquirePartitionLease(partitionRoot); %#ok<NASGU>
            receiptPath = bms.data.VerifiedSourceCsvCleanupService.receiptPath(partitionRoot);
            if isfile(receiptPath)
                    previous = bms.io.JsonFile.read(receiptPath);
                if strcmp(char(string(previous.status)), 'committed')
                    bms.data.VerifiedSourceCsvCleanupService.assertReceiptBinding( ...
                        previous, cacheVersion, configHash, receiptPath, cfg);
                    bms.data.VerifiedSourceCsvCleanupService.assertCommittedReceiptState( ...
                        previous, receiptPath);
                    if ~bms.data.ArchiveExtractService.verifyArchiveProof( ...
                            previous.archive_proof)
                        error('BMS:CacheSourceCleanup:RecoveryArchiveChanged', ...
                            'Recovery ZIP changed after the existing cleanup: %s', receiptPath);
                    end
                    currentSources = cellstr(string({records.source_path}));
                    previousSources = cellstr(string({previous.files.source_path}));
                    if ~all(ismember(lower(string(currentSources)), ...
                            lower(string(previousSources))))
                        error('BMS:CacheSourceCleanup:CommittedReceiptExtensionForbidden', ...
                            ['A committed daily receipt cannot be overwritten with new source ' ...
                             'paths. Restore/re-extract and review the whole day explicitly.']);
                    end
                    if any(cellfun(@isfile, currentSources))
                        previous = bms.data.VerifiedSourceCsvCleanupService.commitReceipt( ...
                            receiptPath, previous, cfg);
                        result.status = previous.status;
                        result.receipt_path = receiptPath;
                        result.deleted_count = previous.deleted_count;
                        result.deleted_bytes = previous.deleted_bytes;
                    else
                        result.status = 'already_archived';
                        result.receipt_path = receiptPath;
                    end
                    return;
                else
                    bms.data.VerifiedSourceCsvCleanupService.resumeReceipt( ...
                        receiptPath, previous, cfg, cacheVersion, configHash);
                end
            end

            statuses = cellstr(string({records.status}));
            failed = strcmp(statuses, 'failed');
            if any(failed)
                error('BMS:CacheSourceCleanup:PartitionCacheFailed', ...
                    'At least one eligible cache failed for %s; no CSV was deleted.', ...
                    char(string(day)));
            end
            present = arrayfun(@(rec) isfield(rec, 'source_present') ...
                && logical(rec.source_present) && isfile(char(string(rec.source_path))), records);
            records = records(present);
            if isempty(records)
                result.status = 'already_archived';
                result.receipt_path = receiptPath;
                return;
            end
            validStatus = ismember(cellstr(string({records.status})), ...
                {'created','reused','rebuilt'});
            if ~all(validStatus)
                error('BMS:CacheSourceCleanup:PartitionNotClosed', ...
                    'Partition contains a cache record that is not committed.');
            end
            sourceFiles = cellstr(string({records.source_path}));
            selectedPaths = bms.data.JiulongjiangCsvDataSource. ...
                configuredCleanupCsvPaths(csvDir, cfg);
            selectedKeys = lower(string(cellfun(@(p) ...
                bms.data.VerifiedSourceCsvCleanupService.canonicalPath(p), ...
                selectedPaths, 'UniformOutput', false)));
            sourceKeys = lower(string(cellfun(@(p) ...
                bms.data.VerifiedSourceCsvCleanupService.canonicalPath(p), ...
                sourceFiles, 'UniformOutput', false)));
            if isempty(selectedKeys) || ~all(ismember(sourceKeys, selectedKeys))
                error('BMS:CacheSourceCleanup:SourceOutsideConfiguredScope', ...
                    ['Cleanup records contain a CSV that the active bridge runtime ' ...
                     'would not select from this daily partition.']);
            end
            for i = 1:numel(records)
                source = sourceFiles{i};
                sourceInfo = bms.data.CacheManager.buildSourceRecords({source});
                if isempty(sourceInfo) || ~logical(sourceInfo.exists) ...
                        || double(sourceInfo.bytes) ~= double(records(i).source_bytes) ...
                        || ~strcmp(char(string(sourceInfo.modified_at)), ...
                            char(string(records(i).source_modified_at)))
                    error('BMS:CacheSourceCleanup:SourceChanged', ...
                        'CSV changed after cache publication: %s', source);
                end
                if ~bms.data.JiulongjiangCsvDataSource.validateStandaloneRawCache( ...
                        records(i).cache_path, cfg)
                    error('BMS:CacheSourceCleanup:CacheValidationFailed', ...
                        'Cache is not independently loadable: %s', records(i).cache_path);
                end
            end
            archiveProof = bms.data.ArchiveExtractService.verifyRecoveryForFiles( ...
                root, day, cfg, sourceFiles);
            cleanupScope = bms.data.JiulongjiangCsvDataSource. ...
                configuredCleanupSourceScope(cfg);
            receiptId = char(java.util.UUID.randomUUID());
            entries = repmat(bms.data.VerifiedSourceCsvCleanupService.emptyEntry(), ...
                1, numel(records));
            for i = 1:numel(records)
                source = char(string(records(i).source_path));
                [folder, name, ext] = fileparts(source);
                temp = fullfile(folder, sprintf('.%s%s.bmsdelete.%s', ...
                    name, ext, receiptId));
                meta = bms.io.JsonFile.read(records(i).metadata_path);
                entries(i) = struct( ...
                    'source_path', source, ...
                    'temporary_path', temp, ...
                    'source_bytes', double(records(i).source_bytes), ...
                    'source_modified_at', char(string(records(i).source_modified_at)), ...
                    'cache_path', char(string(records(i).cache_path)), ...
                    'metadata_path', char(string(records(i).metadata_path)), ...
                    'cache_bytes', double(records(i).cache_bytes), ...
                    'pair_id', bms.data.VerifiedSourceCsvCleanupService.fieldText(meta, 'pair_id'), ...
                    'mat_bytes', bms.data.VerifiedSourceCsvCleanupService.fieldDouble(meta, 'mat_bytes'), ...
                    'state', 'pending', 'renamed_at', '', 'deleted_at', '', ...
                    'error_message', '');
            end
            receipt = struct( ...
                'schema_version', 2, ...
                'receipt_type', 'verified_cache_source_cleanup', ...
                'receipt_id', receiptId, ...
                'status', 'prepared', ...
                'mode', options.mode, ...
                'commit_scope', options.commit_scope, ...
                'recovery_policy', options.recovery_policy, ...
                'confirmation', options.confirmation, ...
                'confirmed_at', options.confirmed_at, ...
                'day', char(string(day)), ...
                'partition_root', partitionRoot, ...
                'csv_dir', char(string(csvDir)), ...
                'cache_version', char(string(cacheVersion)), ...
                'config_hash', char(string(configHash)), ...
                'cleanup_scope_hash', cleanupScope.hash, ...
                'cleanup_scope_count', cleanupScope.count, ...
                'cleanup_scope_ids', {cleanupScope.ids}, ...
                'prepared_at', datestr(datetime('now'), 'yyyy-mm-dd HH:MM:ss'), ...
                'committed_at', '', ...
                'deleted_count', 0, ...
                'deleted_bytes', 0, ...
                'archive_proof', archiveProof, ...
                'files', entries, ...
                'error_identifier', '', ...
                'error_message', '');
            bms.core.Logger.writeJson(receiptPath, receipt);
            receipt = bms.data.VerifiedSourceCsvCleanupService.commitReceipt( ...
                receiptPath, receipt, cfg);
            result.status = receipt.status;
            result.receipt_path = receiptPath;
            result.deleted_count = receipt.deleted_count;
            result.deleted_bytes = receipt.deleted_bytes;
        end
    end

    methods (Static, Access = private)
        function receipt = resumeReceipt(receiptPath, receipt, cfg, cacheVersion, configHash)
            bms.data.VerifiedSourceCsvCleanupService.assertReceiptBinding( ...
                receipt, cacheVersion, configHash, receiptPath, cfg);
            if ~bms.data.ArchiveExtractService.verifyArchiveProof(receipt.archive_proof)
                error('BMS:CacheSourceCleanup:RecoveryArchiveChanged', ...
                    'Recovery ZIP changed; interrupted cleanup cannot continue: %s', receiptPath);
            end
            receipt = bms.data.VerifiedSourceCsvCleanupService.commitReceipt( ...
                receiptPath, receipt, cfg);
        end

        function receipt = commitReceipt(receiptPath, receipt, cfg)
            originalStatus = char(string(receipt.status));
            archivePath = char(string(receipt.archive_proof.archive_path));
            try
                zipGuard = java.util.zip.ZipFile(archivePath); %#ok<NASGU>
                zipGuardCleanup = onCleanup(@() zipGuard.close()); %#ok<NASGU>
            catch ME
                error('BMS:CacheSourceCleanup:RecoveryArchiveLockFailed', ...
                    'Unable to lock the recovery ZIP for cleanup: %s (%s)', ...
                    archivePath, ME.message);
            end
            if ~bms.data.ArchiveExtractService.verifyArchiveProof( ...
                    receipt.archive_proof, true)
                error('BMS:CacheSourceCleanup:RecoveryArchiveChanged', ...
                    'Recovery ZIP changed before CSV deletion: %s', receiptPath);
            end
            entries = receipt.files;
            renamed = false(1, numel(entries));
            try
                receipt.status = 'renaming';
                bms.core.Logger.writeJson(receiptPath, receipt);
                for i = 1:numel(entries)
                    source = char(string(entries(i).source_path));
                    temp = char(string(entries(i).temporary_path));
                    bms.data.VerifiedSourceCsvCleanupService.assertEntryPaths( ...
                        receipt, entries(i));
                    bms.data.VerifiedSourceCsvCleanupService.assertCacheEntry( ...
                        receipt, entries(i), cfg);
                    sourceExists = isfile(source);
                    tempExists = isfile(temp);
                    if sourceExists && tempExists
                        error('BMS:CacheSourceCleanup:DuplicatePendingSource', ...
                            'Both original and pending-delete files exist: %s', source);
                    elseif sourceExists
                        info = bms.data.CacheManager.buildSourceRecords({source});
                        if double(info.bytes) ~= double(entries(i).source_bytes) ...
                                || ~strcmp(char(string(info.modified_at)), ...
                                    char(string(entries(i).source_modified_at)))
                            error('BMS:CacheSourceCleanup:SourceChanged', ...
                                'CSV changed before deletion commit: %s', source);
                        end
                        bms.data.VerifiedSourceCsvCleanupService. ...
                            assertCurrentContentMatchesRecovery( ...
                            receipt, entries(i), source, ...
                            'BMS:CacheSourceCleanup:SourceContentChanged');
                        [ok, message] = movefile(source, temp);
                        if ~ok
                            error('BMS:CacheSourceCleanup:RenameFailed', ...
                                'Unable to stage CSV for deletion: %s (%s)', source, message);
                        end
                        renamed(i) = true;
                        entries(i).state = 'renamed';
                        entries(i).renamed_at = datestr(datetime('now'), 'yyyy-mm-dd HH:MM:ss');
                        bms.data.VerifiedSourceCsvCleanupService. ...
                            assertCurrentContentMatchesRecovery( ...
                            receipt, entries(i), temp, ...
                            'BMS:CacheSourceCleanup:StagedSourceContentChanged');
                    elseif tempExists
                        tempInfo = bms.data.CacheManager.buildSourceRecords({temp});
                        if double(tempInfo.bytes) ~= double(entries(i).source_bytes) ...
                                || ~strcmp(char(string(tempInfo.modified_at)), ...
                                    char(string(entries(i).source_modified_at)))
                            error('BMS:CacheSourceCleanup:StagedSourceChanged', ...
                                ['Pending-delete CSV no longer matches the source bound ' ...
                                 'to the cleanup receipt: %s'], temp);
                        end
                        bms.data.VerifiedSourceCsvCleanupService. ...
                            assertCurrentContentMatchesRecovery( ...
                            receipt, entries(i), temp, ...
                            'BMS:CacheSourceCleanup:StagedSourceContentChanged');
                        renamed(i) = true;
                        entries(i).state = 'renamed_reconciled';
                    else
                        if ~ismember(originalStatus, {'deleting','partial','committed'})
                            error('BMS:CacheSourceCleanup:SourceDisappearedBeforeDelete', ...
                                ['Neither original nor staged CSV exists before the delete ' ...
                                 'phase: %s'], source);
                        end
                        entries(i).state = 'deleted_reconciled';
                        entries(i).deleted_at = datestr(datetime('now'), 'yyyy-mm-dd HH:MM:ss');
                    end
                    receipt.files = entries;
                    bms.core.Logger.writeJson(receiptPath, receipt);
                end
            catch ME
                [rollbackOk, rollbackMessage] = ...
                    bms.data.VerifiedSourceCsvCleanupService.rollbackRenamed( ...
                    entries, renamed);
                if rollbackOk
                    receipt.status = 'rename_failed_rolled_back';
                else
                    receipt.status = 'rename_failed_rollback_incomplete';
                end
                receipt.error_identifier = ME.identifier;
                receipt.error_message = strjoin( ...
                    {ME.message, rollbackMessage}, ' | ');
                receipt.files = entries;
                bms.core.Logger.writeJson(receiptPath, receipt);
                if ~rollbackOk
                    error('BMS:CacheSourceCleanup:RollbackFailed', '%s', ...
                        receipt.error_message);
                end
                rethrow(ME);
            end

            if ~bms.data.ArchiveExtractService.verifyArchiveProof( ...
                    receipt.archive_proof, true)
                [rollbackOk, rollbackMessage] = ...
                    bms.data.VerifiedSourceCsvCleanupService.rollbackRenamed( ...
                    entries, renamed);
                if rollbackOk
                    receipt.status = 'recovery_changed_rolled_back';
                else
                    receipt.status = 'recovery_changed_rollback_incomplete';
                end
                receipt.error_identifier = ...
                    'BMS:CacheSourceCleanup:RecoveryArchiveChanged';
                receipt.error_message = strjoin({ ...
                    'Recovery ZIP changed after staging and before deletion.', ...
                    rollbackMessage}, ' | ');
                receipt.files = entries;
                bms.core.Logger.writeJson(receiptPath, receipt);
                if ~rollbackOk
                    error('BMS:CacheSourceCleanup:RollbackFailed', '%s', ...
                        receipt.error_message);
                end
                error(receipt.error_identifier, '%s', receipt.error_message);
            end
            receipt.status = 'deleting';
            receipt.files = entries;
            bms.core.Logger.writeJson(receiptPath, receipt);
            try
                for i = 1:numel(entries)
                    temp = char(string(entries(i).temporary_path));
                    bms.data.VerifiedSourceCsvCleanupService.assertEntryPaths( ...
                        receipt, entries(i));
                    if isfile(temp)
                        bms.data.VerifiedSourceCsvCleanupService. ...
                            assertCurrentContentMatchesRecovery( ...
                            receipt, entries(i), temp, ...
                            'BMS:CacheSourceCleanup:StagedSourceContentChanged');
                        delete(temp);
                    end
                    if isfile(char(string(entries(i).source_path))) || isfile(temp)
                        error('BMS:CacheSourceCleanup:DeleteFailed', ...
                            'CSV still exists after deletion attempt: %s', entries(i).source_path);
                    end
                    bms.data.VerifiedSourceCsvCleanupService.assertCacheEntry( ...
                        receipt, entries(i), cfg);
                    entries(i).state = 'deleted';
                    if isempty(entries(i).deleted_at)
                        entries(i).deleted_at = datestr(datetime('now'), 'yyyy-mm-dd HH:MM:ss');
                    end
                    receipt.files = entries;
                    receipt.deleted_count = nnz(ismember(cellstr(string({entries.state})), ...
                        {'deleted','deleted_reconciled'}));
                    receipt.deleted_bytes = sum(double([entries(ismember( ...
                        cellstr(string({entries.state})), ...
                        {'deleted','deleted_reconciled'})).source_bytes]));
                    bms.core.Logger.writeJson(receiptPath, receipt);
                end
            catch ME
                receipt.status = 'partial';
                receipt.error_identifier = ME.identifier;
                receipt.error_message = ME.message;
                receipt.files = entries;
                bms.core.Logger.writeJson(receiptPath, receipt);
                rethrow(ME);
            end
            receipt.status = 'committed';
            receipt.committed_at = datestr(datetime('now'), 'yyyy-mm-dd HH:MM:ss');
            receipt.error_identifier = '';
            receipt.error_message = '';
            receipt.deleted_count = numel(entries);
            receipt.deleted_bytes = sum(double([entries.source_bytes]));
            receipt.files = entries;
            bms.core.Logger.writeJson(receiptPath, receipt);
        end

        function assertCacheEntry(receipt, entry, cfg)
            cachePath = char(string(entry.cache_path));
            sourcePath = char(string(entry.source_path));
            [~, sourceBase] = fileparts(sourcePath);
            adapter = bms.data.JiulongjiangCsvDataSource.adapterFromConfig(cfg);
            expectedCacheDir = bms.data.JiulongjiangCsvDataSource.resolveCacheDir( ...
                char(string(receipt.csv_dir)), adapter);
            expectedCache = fullfile(expectedCacheDir, [sourceBase '.mat']);
            if ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                    cachePath), ...
                    bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                    expectedCache))
                error('BMS:CacheSourceCleanup:UnexpectedCachePath', ...
                    'Cache path is not the source CSV''s configured cache path: %s', ...
                    cachePath);
            end
            if ~bms.data.JiulongjiangCsvDataSource.validateStandaloneRawCache(cachePath, cfg)
                error('BMS:CacheSourceCleanup:CacheValidationFailed', ...
                    'Cache pair failed standalone validation: %s', cachePath);
            end
            meta = bms.io.JsonFile.read(entry.metadata_path);
            if ~isfield(meta, 'source_records')
                error('BMS:CacheSourceCleanup:CacheSourceIdentityMissing', ...
                    'Cache metadata has no source identity: %s', cachePath);
            end
            records = bms.data.CacheManager.normalizeSourceRecords(meta.source_records);
            if numel(records) ~= 1 ...
                    || ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        records(1).path), ...
                        bms.data.VerifiedSourceCsvCleanupService.canonicalPath(sourcePath)) ...
                    || ~logical(records(1).exists) ...
                    || double(records(1).bytes) ~= double(entry.source_bytes) ...
                    || ~strcmp(char(string(records(1).modified_at)), ...
                        char(string(entry.source_modified_at)))
                error('BMS:CacheSourceCleanup:CacheSourceIdentityMismatch', ...
                    'Cache metadata is not bound to the source CSV receipt: %s', ...
                    cachePath);
            end
            payload = load(cachePath, 'meta');
            if ~isfield(payload, 'meta') || ~isstruct(payload.meta) ...
                    || ~isfield(payload.meta, 'src') ...
                    || ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        payload.meta.src), ...
                        bms.data.VerifiedSourceCsvCleanupService.canonicalPath(sourcePath)) ...
                    || ~isfield(payload.meta, 'size') ...
                    || double(payload.meta.size) ~= double(entry.source_bytes) ...
                    || ~isfield(payload.meta, 'mtime') ...
                    || ~strcmp(datestr(double(payload.meta.mtime), ...
                        'yyyy-mm-dd HH:MM:ss'), ...
                        char(string(entry.source_modified_at)))
                error('BMS:CacheSourceCleanup:MatSourceIdentityMismatch', ...
                    'MAT cache is not bound to the source CSV receipt: %s', cachePath);
            end
            pairId = char(string(entry.pair_id));
            entryMatBytes = double(entry.mat_bytes);
            entryCacheBytes = double(entry.cache_bytes);
            cacheInfo = dir(cachePath);
            actualPairBytes = ...
                bms.data.JiulongjiangCsvDataSource.cachePairBytes(cachePath);
            if isempty(pairId) || ~isfinite(entryMatBytes) || entryMatBytes <= 0 ...
                    || ~isfinite(entryCacheBytes) || entryCacheBytes <= 0 ...
                    || isempty(cacheInfo) || double(cacheInfo(1).bytes) ~= entryMatBytes ...
                    || actualPairBytes ~= entryCacheBytes ...
                    || ~strcmp(bms.data.VerifiedSourceCsvCleanupService.fieldText(meta, 'pair_id'), ...
                        pairId) ...
                    || bms.data.VerifiedSourceCsvCleanupService.fieldDouble(meta, 'mat_bytes') ...
                        ~= entryMatBytes
                error('BMS:CacheSourceCleanup:CachePairChanged', ...
                    'Cache pair identity changed during cleanup: %s', cachePath);
            end
        end

        function assertReceiptBinding(receipt, cacheVersion, configHash, receiptPath, cfg)
            cleanupScope = bms.data.JiulongjiangCsvDataSource. ...
                configuredCleanupSourceScope(cfg);
            required = {'schema_version','receipt_type','receipt_id','status', ...
                'mode','commit_scope','recovery_policy','confirmation','confirmed_at', ...
                'day','partition_root','csv_dir','cache_version','config_hash', ...
                'cleanup_scope_hash','cleanup_scope_count','cleanup_scope_ids', ...
                'archive_proof','files'};
            receiptScopeIds = {};
            if isstruct(receipt) && isscalar(receipt) ...
                    && isfield(receipt, 'cleanup_scope_ids')
                receiptScopeIds = cellstr(lower(string(receipt.cleanup_scope_ids(:))));
                receiptScopeIds = sort(unique(receiptScopeIds));
            end
            if ~isstruct(receipt) || ~isscalar(receipt) || ~all(isfield(receipt, required)) ...
                    || double(receipt.schema_version) ~= 2 ...
                    || ~strcmp(char(string(receipt.receipt_type)), ...
                        'verified_cache_source_cleanup') ...
                    || ~strcmp(char(string(receipt.mode)), 'verified_extracted_csv') ...
                    || ~strcmp(char(string(receipt.commit_scope)), 'day') ...
                    || ~strcmp(char(string(receipt.recovery_policy)), 'verified_archive') ...
                    || ~strcmp(char(string(receipt.confirmation)), ...
                        'DELETE_VERIFIED_EXTRACTED_CSV') ...
                    || isempty(strtrim(char(string(receipt.confirmed_at)))) ...
                    || ~strcmp(char(string(receipt.cache_version)), char(string(cacheVersion))) ...
                    || ~strcmp(char(string(receipt.config_hash)), char(string(configHash))) ...
                    || ~strcmp(char(string(receipt.cleanup_scope_hash)), cleanupScope.hash) ...
                    || double(receipt.cleanup_scope_count) ~= cleanupScope.count ...
                    || numel(receiptScopeIds) ~= cleanupScope.count ...
                    || ~isequal(receiptScopeIds(:), cleanupScope.ids(:))
                error('BMS:CacheSourceCleanup:ReceiptBindingMismatch', ...
                    ['Cleanup receipt does not match the current cache/point scope ' ...
                     'contract: %s'], receiptPath);
            end
            canonicalReceipt = bms.data.VerifiedSourceCsvCleanupService.receiptPath( ...
                char(string(receipt.partition_root)));
            if ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                    canonicalReceipt), ...
                    bms.data.VerifiedSourceCsvCleanupService.canonicalPath(receiptPath)) ...
                    || ~bms.data.VerifiedSourceCsvCleanupService.isPathInside( ...
                        char(string(receipt.csv_dir)), ...
                        char(string(receipt.partition_root)))
                error('BMS:CacheSourceCleanup:ReceiptPathMismatch', ...
                    'Cleanup receipt paths are outside their declared partition: %s', receiptPath);
            end
            proofRequired = {'day','output_root','extraction_manifest_path','files'};
            proof = receipt.archive_proof;
            expectedManifest = fullfile(char(string(receipt.partition_root)), ...
                '.bms_extract_manifest.json');
            if ~isstruct(proof) || ~isscalar(proof) ...
                    || ~all(isfield(proof, proofRequired)) ...
                    || ~strcmp(char(string(proof.day)), char(string(receipt.day))) ...
                    || ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        proof.output_root), ...
                        bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        receipt.partition_root)) ...
                    || ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        proof.extraction_manifest_path), ...
                        bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        expectedManifest))
                error('BMS:CacheSourceCleanup:ReceiptArchiveBindingMismatch', ...
                    'Cleanup receipt recovery proof is not bound to its day/partition.');
            end
            for i = 1:numel(receipt.files)
                bms.data.VerifiedSourceCsvCleanupService.assertEntryPaths( ...
                    receipt, receipt.files(i));
            end
            proofFiles = receipt.archive_proof.files;
            proofSources = cellstr(string({proofFiles.path}));
            entrySources = cellstr(string({receipt.files.source_path}));
            normalizedEntries = unique(lower(string(entrySources)));
            normalizedProof = unique(lower(string(proofSources)));
            if numel(normalizedEntries) ~= numel(entrySources) ...
                    || numel(normalizedEntries) ~= numel(normalizedProof) ...
                    || ~all(ismember(normalizedEntries, normalizedProof)) ...
                    || ~all(ismember(normalizedProof, normalizedEntries))
                error('BMS:CacheSourceCleanup:ReceiptArchiveMismatch', ...
                    'Cleanup receipt entries are not a subset of its verified archive proof.');
            end
            for i = 1:numel(receipt.files)
                [~, sourceBase] = fileparts(char(string(receipt.files(i).source_path)));
                [~, cacheBase] = fileparts(char(string(receipt.files(i).cache_path)));
                proofIndex = find(strcmpi(proofSources, ...
                    char(string(receipt.files(i).source_path))), 1);
                if isempty(proofIndex) || ~strcmpi(sourceBase, cacheBase) ...
                        || double(proofFiles(proofIndex).bytes) ...
                            ~= double(receipt.files(i).source_bytes)
                    error('BMS:CacheSourceCleanup:ReceiptArchiveMismatch', ...
                        'Cleanup receipt source/cache/archive identity does not close.');
                end
            end
        end

        function assertCommittedReceiptState(receipt, receiptPath)
            entries = receipt.files;
            states = cellstr(string({entries.state}));
            expectedBytes = sum(double([entries.source_bytes]));
            committedAt = '';
            if isfield(receipt, 'committed_at')
                committedAt = strtrim(char(string(receipt.committed_at)));
            end
            valid = ~isempty(entries) ...
                && strcmp(char(string(receipt.status)), 'committed') ...
                && ~isempty(committedAt) ...
                && isfield(receipt, 'deleted_count') ...
                && double(receipt.deleted_count) == numel(entries) ...
                && isfield(receipt, 'deleted_bytes') ...
                && double(receipt.deleted_bytes) == expectedBytes ...
                && all(ismember(states, {'deleted','deleted_reconciled'}));
            if ~valid
                error('BMS:CacheSourceCleanup:CommittedReceiptInvalid', ...
                    'Committed cleanup receipt state/counts do not close: %s', ...
                    receiptPath);
            end
        end

        function cleanup = acquirePartitionLease(partitionRoot)
            partitionRoot = char(string(partitionRoot));
            [outputRoot, partitionName] = fileparts(partitionRoot);
            lockRoot = fullfile(outputRoot, '.bms_cache_source_cleanup_locks');
            bms.data.DataLayoutResolver.ensureDir(lockRoot);
            safeName = regexprep(partitionName, '[^A-Za-z0-9_.-]', '_');
            lockPath = fullfile(lockRoot, [safeName '.lock']);
            try
                cleanup = bms.core.DirectoryLeaseLock.acquire( ...
                    lockPath, struct('recover_stale', true, 'stale_hours', 24), ...
                    struct('partition_root', partitionRoot, ...
                    'purpose', 'verified_cache_source_cleanup'));
            catch ME
                if strcmp(ME.identifier, 'BMS:DirectoryLeaseLock:Locked')
                    error('BMS:CacheSourceCleanup:Locked', ...
                        'Another cleanup task owns this daily partition: %s', ...
                        partitionRoot);
                end
                rethrow(ME);
            end
        end

        function assertEntryPaths(receipt, entry)
            source = char(string(entry.source_path));
            temp = char(string(entry.temporary_path));
            cachePath = char(string(entry.cache_path));
            metadataPath = char(string(entry.metadata_path));
            csvDir = char(string(receipt.csv_dir));
            partitionRoot = char(string(receipt.partition_root));
            [sourceFolder, sourceName, sourceExt] = fileparts(source);
            expectedTemp = fullfile(sourceFolder, sprintf('.%s%s.bmsdelete.%s', ...
                sourceName, sourceExt, char(string(receipt.receipt_id))));
            if ~bms.data.VerifiedSourceCsvCleanupService.isPathInside(source, csvDir) ...
                    || ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath(temp), ...
                        bms.data.VerifiedSourceCsvCleanupService.canonicalPath(expectedTemp)) ...
                    || ~bms.data.VerifiedSourceCsvCleanupService.isPathInside( ...
                        cachePath, partitionRoot) ...
                    || ~strcmpi(bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        metadataPath), ...
                        bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                        bms.data.CacheManager.metadataPath(cachePath)))
                error('BMS:CacheSourceCleanup:UnsafeReceiptPath', ...
                    'Cleanup receipt contains a path outside its verified daily partition.');
            end
        end

        function assertCurrentContentMatchesRecovery(receipt, entry, actualPath, identifier)
            source = bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                entry.source_path);
            proofFiles = receipt.archive_proof.files;
            matches = false(1, numel(proofFiles));
            for i = 1:numel(proofFiles)
                matches(i) = strcmpi(source, ...
                    bms.data.VerifiedSourceCsvCleanupService.canonicalPath( ...
                    proofFiles(i).path));
            end
            if nnz(matches) ~= 1
                error('BMS:CacheSourceCleanup:ReceiptArchiveBindingMismatch', ...
                    'Cleanup source has no unique recovery-proof entry: %s', source);
            end
            try
                bms.data.ArchiveExtractService.verifyFileAgainstProofEntry( ...
                    actualPath, proofFiles(find(matches, 1)));
            catch ME
                error(identifier, ...
                    'CSV content changed after recovery proof creation: %s (%s)', ...
                    char(string(actualPath)), ME.message);
            end
        end

        function tf = isPathInside(pathValue, root)
            pathValue = bms.data.VerifiedSourceCsvCleanupService.canonicalPath(pathValue);
            root = regexprep(bms.data.VerifiedSourceCsvCleanupService. ...
                canonicalPath(root), '[\\/]+$', '');
            tf = strcmpi(pathValue, root) || startsWith(lower(pathValue), ...
                lower([root filesep]));
        end

        function value = canonicalPath(pathValue)
            try
                value = char(java.io.File(char(string(pathValue))).getCanonicalPath());
            catch
                value = char(string(pathValue));
            end
        end

        function path = findReceiptAncestor(startPath)
            root = char(string(startPath));
            path = '';
            for i = 1:12
                candidate = bms.data.VerifiedSourceCsvCleanupService.receiptPath(root);
                if isfile(candidate)
                    path = candidate;
                    return;
                end
                parent = fileparts(root);
                if isempty(parent) || strcmp(parent, root), return; end
                root = parent;
            end
        end

        function [ok, message] = rollbackRenamed(entries, renamed)
            ok = true;
            messages = {};
            lastRenamed = find(renamed, 1, 'last');
            if isempty(lastRenamed)
                message = '';
                return;
            end
            for i = lastRenamed:-1:1
                source = char(string(entries(i).source_path));
                temp = char(string(entries(i).temporary_path));
                if isfile(temp) && ~isfile(source)
                    [moved, detail] = movefile(temp, source);
                    if ~moved
                        ok = false;
                        messages{end+1} = sprintf('%s: %s', source, detail); %#ok<AGROW>
                    end
                end
            end
            message = strjoin(messages, '; ');
        end

        function value = fieldText(s, name)
            value = '';
            if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
                value = char(string(s.(name)));
            end
        end

        function value = fieldDouble(s, name)
            value = NaN;
            if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
                value = double(s.(name));
            end
        end

        function entry = emptyEntry()
            entry = struct('source_path', '', 'temporary_path', '', ...
                'source_bytes', 0, 'source_modified_at', '', ...
                'cache_path', '', 'metadata_path', '', 'cache_bytes', 0, ...
                'pair_id', '', 'mat_bytes', NaN, 'state', 'pending', ...
                'renamed_at', '', 'deleted_at', '', 'error_message', '');
        end
    end
end
