function summary = run_hongtang_typhoon_highfreq(dataRoot, startDate, endDate, configPath)
%RUN_HONGTANG_TYPHOON_HIGHFREQ Recompute the supported Hongtang event modules.
%   This entry point intentionally excludes WIM and the Jikang low-frequency
%   modules (strain, tower tilt, and bearing displacement).  It is intended
%   for an isolated, timestamp-trimmed typhoon data root prepared from the
%   Donghua daily exports.  Missing Q2 report sections are cleared later by
%   the dedicated incremental report builder; old quarterly values must never
%   be used as a fallback.

    arguments
        dataRoot (1, :) char
        startDate (1, :) char
        endDate (1, :) char
        configPath (1, :) char = ''
    end

    projectRoot = fileparts(fileparts(mfilename('fullpath')));
    if isempty(configPath)
        configPath = fullfile(projectRoot, 'config', 'hongtang_config.json');
    end

    assert(isfolder(dataRoot), 'TyphoonRun:MissingDataRoot', ...
        'Data root does not exist: %s', dataRoot);
    assert(isfile(configPath), 'TyphoonRun:MissingConfig', ...
        'Config does not exist: %s', configPath);

    cfg = load_config(configPath);
    if ~isfield(cfg, 'notify') || ~isstruct(cfg.notify)
        cfg.notify = struct();
    end
    cfg.notify.enabled = false;
    if ~isfield(cfg, 'plot_common') || ~isstruct(cfg.plot_common)
        cfg.plot_common = struct();
    end
    cfg.plot_common.dynamic_raw_sampling_mode = 'full';
    cfg.plot_common.dynamic_group_sampling_mode = 'full';
    cfg.plot_common.dynamic_raw_render_mode = 'line';
    cfg.plot_common.dynamic_raw_disable_emf = true;
    cfg.plot_common.dynamic_raw_line_width = 1.0;
    cfg.plot_common.gap_mode = 'connect';
    cfg.plot_common.save_emf = false;
    cfg.plot_common.save_fig = true;
    cfg.plot_common.lightweight_fig = true;
    cfg.plot_common.append_timestamp = false;

    opts = struct( ...
        'precheck_zip_count', false, ...
        'doUnzip', false, ...
        'doRenameCsv', false, ...
        'doRemoveHeader', false, ...
        'doResample', false, ...
        'doLowfreqSync', false, ...
        'doTemp', false, ...
        'doHumidity', false, ...
        'doRainfall', false, ...
        'doGNSS', false, ...
        'doWind', true, ...
        'doEq', true, ...
        'doWIM', false, ...
        'doDeflect', false, ...
        'doBearingDisplacement', false, ...
        'doTilt', false, ...
        'doAccel', true, ...
        'doAccelSpectrum', true, ...
        'doCableAccel', true, ...
        'doCableAccelSpectrum', true, ...
        'doRenameCrk', false, ...
        'doCrack', false, ...
        'doStrain', false, ...
        'doDynStrainBoxplot', false, ...
        'doDynStrainLowpassBoxplot', false, ...
        'buildDataIndex', true, ...
        'buildStatsInventory', true, ...
        'buildRunHealthReport', true);

    summary = run_all(dataRoot, startDate, endDate, opts, cfg);
end
