function summary = run_matlab_coverage(outputRoot, target)
%RUN_MATLAB_COVERAGE Run MATLAB tests with production-source coverage enabled.
%   The command writes Cobertura XML, JSON/text summaries, and test results.
%   TARGET is "all" or "smoke". Instrumentation is collected through the
%   condition level; Cobertura exposes interoperable line/branch totals.

    if nargin < 1 || strlength(string(outputRoot)) == 0
        outputRoot = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
            'outputs', 'coverage');
    end
    if nargin < 2 || strlength(string(target)) == 0
        target = "all";
    end

    repo = fileparts(fileparts(mfilename('fullpath')));
    outputRoot = char(java.io.File(char(outputRoot)).getCanonicalPath());
    if ~isfolder(outputRoot)
        mkdir(outputRoot);
    end
    addpath(repo, fullfile(repo, 'ui'), fullfile(repo, 'config'), ...
        fullfile(repo, 'pipeline'), fullfile(repo, 'analysis'), ...
        fullfile(repo, 'scripts'), fullfile(repo, 'tests'), '-begin');

    suite = coverageSuite(repo, string(target));
    coberturaPath = fullfile(outputRoot, 'matlab-cobertura.xml');
    resultsPath = fullfile(outputRoot, 'matlab-test-results.csv');
    jsonPath = fullfile(outputRoot, 'matlab-coverage-summary.json');
    textPath = fullfile(outputRoot, 'matlab-coverage-summary.txt');

    import matlab.unittest.plugins.CodeCoveragePlugin
    import matlab.unittest.plugins.codecoverage.CoberturaFormat

    runner = testrunner("textoutput");
    sourceFolders = { ...
        fullfile(repo, '+bms'), ...
        fullfile(repo, 'analysis'), ...
        fullfile(repo, 'pipeline'), ...
        fullfile(repo, 'ui'), ...
        fullfile(repo, 'config'), ...
        fullfile(repo, 'scripts') ...
        };
    sourceFolders = sourceFolders(cellfun(@isfolder, sourceFolders));
    coveragePlugin = CodeCoveragePlugin.forFolder(sourceFolders, ...
        'IncludingSubfolders', true, ...
        'MetricLevel', 'condition', ...
        'Producing', CoberturaFormat(coberturaPath));
    runner.addPlugin(coveragePlugin);
    results = runner.run(suite);
    writetable(table(results), resultsPath);

    summary = buildSummary(results, coberturaPath, char(target));
    writeUtf8(jsonPath, jsonencode(summary, PrettyPrint=true));
    text = sprintf([ ...
        'Guanbing MATLAB coverage baseline\n' ...
        'target: %s\n' ...
        'tests: %d total, %d passed, %d failed, %d incomplete\n' ...
        'statement/line: %.2f%% (%d/%d)\n' ...
        'decision/branch: %.2f%% (%d/%d)\n' ...
        'metric level collected: condition\n' ...
        'Cobertura: %s\n'], ...
        summary.target, summary.tests.total, summary.tests.passed, ...
        summary.tests.failed, summary.tests.incomplete, ...
        100 * summary.coverage.line_rate, summary.coverage.lines_covered, ...
        summary.coverage.lines_valid, 100 * summary.coverage.branch_rate, ...
        summary.coverage.branches_covered, summary.coverage.branches_valid, ...
        coberturaPath);
    writeUtf8(textPath, text);
    fprintf('%s', text);

    if summary.tests.failed > 0
        error('BMS:Coverage:MatlabTestsFailed', ...
            '%d MATLAB coverage test(s) failed.', summary.tests.failed);
    end
end

function suite = coverageSuite(repo, target)
    switch lower(char(target))
        case 'all'
            suite = testsuite(fullfile(repo, 'tests'));
        case 'smoke'
            files = { ...
                fullfile(repo, 'tests', 'test_config_utils.m'), ...
                fullfile(repo, 'tests', 'test_module_registry.m'), ...
                fullfile(repo, 'tests', 'test_workbench_cleaning_threshold_contract.m') ...
                };
            suite = testsuite(files);
        otherwise
            error('BMS:Coverage:UnknownTarget', ...
                'Unknown MATLAB coverage target: %s', target);
    end
end

function summary = buildSummary(results, coberturaPath, target)
    if ~isfile(coberturaPath)
        error('BMS:Coverage:MissingCobertura', ...
            'MATLAB coverage plugin did not create %s.', coberturaPath);
    end
    doc = xmlread(coberturaPath);
    root = doc.getDocumentElement();

    summary = struct();
    summary.schema_version = 1;
    summary.generated_at = char(datetime('now', 'Format', "yyyy-MM-dd'T'HH:mm:ssXXX"));
    summary.target = target;
    summary.metric_level = 'condition';
    summary.tests = struct( ...
        'total', numel(results), ...
        'passed', sum([results.Passed]), ...
        'failed', sum([results.Failed]), ...
        'incomplete', sum([results.Incomplete] & ~[results.Failed]));
    summary.coverage = struct( ...
        'line_rate', xmlNumber(root, 'line-rate'), ...
        'branch_rate', xmlNumber(root, 'branch-rate'), ...
        'lines_covered', xmlNumber(root, 'lines-covered'), ...
        'lines_valid', xmlNumber(root, 'lines-valid'), ...
        'branches_covered', xmlNumber(root, 'branches-covered'), ...
        'branches_valid', xmlNumber(root, 'branches-valid'));
    summary.cobertura_file = coberturaPath;
end

function value = xmlNumber(node, name)
    raw = char(node.getAttribute(name));
    value = str2double(raw);
    if ~isfinite(value)
        value = 0;
    end
end

function writeUtf8(path, text)
    fid = fopen(path, 'w', 'n', 'UTF-8');
    if fid < 0
        error('BMS:Coverage:WriteFailed', 'Cannot write %s.', path);
    end
    cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
    fwrite(fid, char(text), 'char');
end
