function run_hongtang_test()
% run_hongtang_test  命令行测试入口，绕过 GUI。
% 用法：在项目根目录执行：
%   addpath(fullfile(pwd,'scripts'));
%   run_hongtang_test();
%
% 说明：
%   - 仅运行加速度频谱（可在 opts 中调整开关）。
%   - 默认读取 config/hongtang_config.json。
%   - 请修改 root/start_date/end_date 为你的数据路径和日期范围。

    addpath(pwd, fullfile(pwd,'config'), fullfile(pwd,'pipeline'), ...
        fullfile(pwd,'analysis'), fullfile(pwd,'scripts'));

    % === 配置这里 ===
    root = 'F:\洪塘数据\2025年12月';      % TODO: 修改为你的数据根目录
    start_date = '2025-01-01';       % TODO: 修改起始日期
    end_date   = '2025-01-02';       % TODO: 修改结束日期
    cfg = load_config(fullfile(pwd,'config','hongtang_config.json'));

    opts = struct( ...
        'precheck_zip_count', false, ...
        'doUnzip', false, ...
        'doRenameCsv', false, ...
        'doRemoveHeader', false, ...
        'doResample', false, ...
        'doTemp', false, ...
        'doHumidity', false, ...
        'doDeflect', false, ...
        'doTilt', false, ...
        'doAccel', false, ...
        'doAccelSpectrum', true, ...   % 仅跑频谱
        'doRenameCrk', false, ...
        'doCrack', false, ...
        'doStrain', false, ...
        'doDynStrainBoxplot', false);

    run_all(root, start_date, end_date, opts, cfg);
end
