function result = validate_zhishan_cable_accel_visual_alternatives()
%VALIDATE_ZHISHAN_CABLE_ACCEL_VISUAL_ALTERNATIVES Validate visual backups.
%   Checks display-only alternative pages and report folders without
%   changing the formal cable-acceleration calculation policy.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
cd(projectRoot);
addpath(genpath(projectRoot));

dataRoot = fullfile('D:\', char([33437 23665 22823 26725 25968 25454]), ...
    ['2026' char(24180) '1-3' char(26376)]);
stableDir = fullfile(dataRoot, 'report_cable_accel_display_recommendation');
lowKeepVsExtremeDir = fullfile(stableDir, 'low_keep_vs_extreme_report');
hybridRecommendedParametersDir = fullfile(stableDir, 'hybrid_recommended_parameters');
refined55ParametersDir = fullfile(stableDir, 'refined55_parameters');
autoVisualSearchDir = fullfile(stableDir, 'auto_visual_search');
autoVisualReviewDir = fullfile(stableDir, 'auto_visual_review');
ultraCleanReviewDir = fullfile(stableDir, 'ultra_clean_review');
strictReportDir = fullfile(stableDir, 'strict_report_candidate');
strictFinalReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([20005 26684 26368 32456 25512 33616 23637 31034])]);
visualPriorityReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([35270 35273 20248 20808 25512 33616 23637 31034])]);
currentReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([24403 21069 26368 20339 25512 33616 23637 31034])]);
cleanerReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([26356 24178 20928 20248 20808 23637 31034])]);
cleanest70ReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([26368 24178 20928 33258 21160 23637 31034])]);
satisfactionAutoReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([28385 24847 24230 33258 21160 25512 33616 23637 31034])]);
lowKeepAutoReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([20302 20445 30041 29575 33258 21160 25512 33616 23637 31034])]);
extremeFallbackReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([26497 38480 24178 20928 22791 36873 23637 31034])]);
hybridRecommendedReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([28151 21512 25512 33616 23637 31034])]);
refined55ReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([28151 21512]) '55' char([25512 33616 23637 31034])]);
autoVisualReportDir = fullfile(dataRoot, [char([26102 31243 26354 32447]) '_' ...
    char([32034 21147 21152 36895 24230]) '_' ...
    char([33258 21160 35270 35273 25512 33616 23637 31034])]);

points = arrayfun(@(k) sprintf('CF-%d', k), 1:8, 'UniformOutput', false);
focusPoints = {'CF-2','CF-7'};
cfg = load_config(fullfile(projectRoot, 'config', 'zhishan_config.json'));

fileChecks = [
    checkCsvRows('current_best_rules_8_rows', ...
        fullfile(stableDir, 'CableAccelCurrentBestDisplay_rules.csv'), 8)
    checkCsvRows('final_display_rules_8_rows', ...
        fullfile(stableDir, 'CableAccelFinalDisplay_rules.csv'), 8)
    checkStrictFinalRules('current_best_rules_strict_candidate', ...
        fullfile(stableDir, 'CableAccelCurrentBestDisplay_rules.csv'))
    checkStrictFinalRules('final_display_rules_strict_candidate', ...
        fullfile(stableDir, 'CableAccelFinalDisplay_rules.csv'))
    checkCsvRows('decisive_display_manifest_8_rows', ...
        fullfile(stableDir, 'decisive_visual_display_export', ...
        'CableAccelDecisiveVisualDisplay_manifest.csv'), 8)
    checkCsvRows('cleaner_report_manifest_8_rows', ...
        fullfile(cleanerReportDir, 'CableAccelDecisiveVisualReport_manifest.csv'), 8)
    checkCsvRows('target70_manifest_8_rows', ...
        fullfile(stableDir, 'target70_display_export', ...
        'CableAccelTarget70Display_manifest.csv'), 8)
    checkCsvRows('target60_manifest_8_rows', ...
        fullfile(stableDir, 'target60_display_export', ...
        'CableAccelTarget60Display_manifest.csv'), 8)
    checkCsvRows('target50_manifest_8_rows', ...
        fullfile(stableDir, 'target50_display_export', ...
        'CableAccelTarget50Display_manifest.csv'), 8)
    checkCsvRows('cleanest70_manifest_8_rows', ...
        fullfile(stableDir, 'cleanest70_display_export', ...
        'CableAccelCleanest70Display_manifest.csv'), 8)
    checkCsvRows('cleanest60_manifest_8_rows', ...
        fullfile(stableDir, 'cleanest60_display_export', ...
        'CableAccelCleanest60Display_manifest.csv'), 8)
    checkCsvRows('cleanest50_manifest_8_rows', ...
        fullfile(stableDir, 'cleanest50_display_export', ...
        'CableAccelCleanest50Display_manifest.csv'), 8)
    checkCsvRows('cleanest70_score_matrix_rows', ...
        fullfile(stableDir, 'cleanest70_display_export', ...
        'CableAccelCleanest70Display_score_matrix.csv'), 56)
    checkCsvRows('cleanest60_score_matrix_rows', ...
        fullfile(stableDir, 'cleanest60_display_export', ...
        'CableAccelCleanest60Display_score_matrix.csv'), 80)
    checkCsvRows('cleanest50_score_matrix_rows', ...
        fullfile(stableDir, 'cleanest50_display_export', ...
        'CableAccelCleanest50Display_score_matrix.csv'), 80)
    checkCsvRows('cleanest70_report_manifest_8_rows', ...
        fullfile(cleanest70ReportDir, 'CableAccelCleanest70Report_manifest.csv'), 8)
    checkCsvRows('satisfaction_auto_report_manifest_8_rows', ...
        fullfile(satisfactionAutoReportDir, ...
        'CableAccelSatisfactionAutoReport_manifest.csv'), 8)
    checkCsvRows('low_keep_auto_report_manifest_8_rows', ...
        fullfile(lowKeepAutoReportDir, ...
        'CableAccelLowKeepAutoReport_manifest.csv'), 8)
    checkCsvRows('extreme_fallback_report_manifest_8_rows', ...
        fullfile(extremeFallbackReportDir, ...
        'CableAccelExtremeFallbackReport_manifest.csv'), 8)
    checkCsvRows('hybrid_recommended_report_manifest_8_rows', ...
        fullfile(hybridRecommendedReportDir, ...
        'CableAccelHybridRecommendedReport_manifest.csv'), 8)
    checkCsvRows('refined55_report_manifest_8_rows', ...
        fullfile(refined55ReportDir, ...
        'CableAccelRefined55Report_manifest.csv'), 8)
    checkCsvRows('auto_visual_report_manifest_8_rows', ...
        fullfile(autoVisualReportDir, ...
        'CableAccelAutoVisualReport_manifest.csv'), 8)
    checkCsvRows('satisfaction_review_manifest_rows', ...
        fullfile(stableDir, 'satisfaction_review', ...
        'CableAccelSatisfactionReview_manifest.csv'), 24)
    checkCsvRows('satisfaction_review_decision_rows', ...
        fullfile(stableDir, 'satisfaction_review', ...
        'CableAccelSatisfactionReview_decision.csv'), 8)
    checkCsvRows('low_keep_tradeoff_manifest_rows', ...
        fullfile(stableDir, 'low_keep_tradeoff_review', ...
        'CableAccelLowKeepTradeoff_manifest.csv'), 24)
    checkCsvRows('low_keep_tradeoff_decision_rows', ...
        fullfile(stableDir, 'low_keep_tradeoff_review', ...
        'CableAccelLowKeepTradeoff_decision.csv'), 8)
    checkCsvRows('low_keep_vs_extreme_decision_rows', ...
        fullfile(lowKeepVsExtremeDir, ...
        'CableAccelLowKeepVsExtreme_decision.csv'), 8)
    checkCsvRows('hybrid_recommended_parameters_rows', ...
        fullfile(hybridRecommendedParametersDir, ...
        'CableAccelHybridRecommended_parameters.csv'), 8)
    checkCsvRows('refined55_parameters_rows', ...
        fullfile(refined55ParametersDir, ...
        'CableAccelRefined55_parameters.csv'), 8)
    checkCsvRows('auto_visual_score_matrix_rows', ...
        fullfile(autoVisualSearchDir, ...
        'CableAccelAutoVisualSearch_score_matrix.csv'), 91)
    checkCsvRows('auto_visual_review_decision_rows', ...
        fullfile(autoVisualReviewDir, ...
        'CableAccelAutoVisualReview_decision.csv'), 8)
    checkCsvRows('ultra_clean_package_manifest_8_rows', ...
        fullfile(ultraCleanReviewDir, ...
        'CableAccelUltraCleanPackage_manifest.csv'), 8)
    checkCsvRows('ultra_clean_review_decision_rows', ...
        fullfile(ultraCleanReviewDir, ...
        'CableAccelUltraCleanReview_decision.csv'), 2)
    checkCsvRows('ultra_clean_sample_matrix_rows', ...
        fullfile(ultraCleanReviewDir, ...
        'CableAccelUltraCleanReview_sample_matrix.csv'), 72)
    checkCsvRows('strict_report_manifest_8_rows', ...
        fullfile(strictReportDir, ...
        'CableAccelStrictReport_manifest.csv'), 8)
    checkCsvRows('strict_report_decision_8_rows', ...
        fullfile(strictReportDir, ...
        'CableAccelStrictReport_decision.csv'), 8)
    checkCsvRows('strict_final_report_manifest_8_rows', ...
        fullfile(strictFinalReportDir, ...
        'CableAccelStrictFinalReport_manifest.csv'), 8)
    checkCsvRows('visual_priority_report_manifest_8_rows', ...
        fullfile(visualPriorityReportDir, ...
        'CableAccelVisualPriorityReport_manifest.csv'), 8)
    checkCsvRows('visual_priority_report_decision_3_rows', ...
        fullfile(visualPriorityReportDir, ...
        'CableAccelVisualPriorityReport_decision.csv'), 3)
    checkImageSet('cleanest70_images', ...
        fullfile(stableDir, 'cleanest70_display_export'), ...
        'CableAccelCleanest70Display_%s_20260301_20260331.jpg', points)
    checkImageSet('cleanest70_report_images', cleanest70ReportDir, ...
        'CableAccelCleanest70Report_%s_20260301_20260331.jpg', points)
    checkImageSet('cleaner_report_images', cleanerReportDir, ...
        'CableAccelDecisiveVisualReport_%s_20260301_20260331.jpg', points)
    checkImageSet('satisfaction_auto_report_images', satisfactionAutoReportDir, ...
        'CableAccelSatisfactionAutoReport_%s_20260301_20260331.jpg', points)
    checkImageSet('low_keep_auto_report_images', lowKeepAutoReportDir, ...
        'CableAccelLowKeepAutoReport_%s_20260301_20260331.jpg', points)
    checkImageSet('extreme_fallback_report_images', extremeFallbackReportDir, ...
        'CableAccelExtremeFallbackReport_%s_20260301_20260331.jpg', points)
    checkImageSet('hybrid_recommended_report_images', hybridRecommendedReportDir, ...
        'CableAccelHybridRecommendedReport_%s_20260301_20260331.jpg', points)
    checkImageSet('refined55_report_images', refined55ReportDir, ...
        'CableAccelRefined55Report_%s_20260301_20260331.jpg', points)
    checkImageSet('auto_visual_report_images', autoVisualReportDir, ...
        'CableAccelAutoVisualReport_%s_20260301_20260331.jpg', points)
    checkImageSet('auto_visual_review_auto_images', autoVisualReviewDir, ...
        'AutoVisual_%s_20260301_20260331.jpg', points)
    checkImageSet('auto_visual_review_refined55_images', autoVisualReviewDir, ...
        'Refined55_%s_20260301_20260331.jpg', points)
    checkImageSet('auto_visual_review_threshold20_images', autoVisualReviewDir, ...
        'ThresholdAbs20_%s_20260301_20260331.jpg', points)
    checkImageSet('ultra_clean_package_images', ultraCleanReviewDir, ...
        'UltraCleanPackage_%s_20260301_20260331.jpg', points)
    checkImageSet('ultra_clean_selected_images', ultraCleanReviewDir, ...
        'UltraCleanSelected_%s_20260301_20260331.jpg', focusPoints)
    checkImageSet('ultra_clean_auto_compare_images', ultraCleanReviewDir, ...
        'AutoVisualCompare_%s_20260301_20260331.jpg', focusPoints)
    checkImageSet('strict_report_images', fullfile(strictReportDir, 'images'), ...
        'CableAccelStrictReport_%s_20260301_20260331.jpg', points)
    checkImageSet('strict_final_report_images', strictFinalReportDir, ...
        'CableAccelStrictFinalReport_%s_20260301_20260331.jpg', points)
    checkImageSet('visual_priority_report_images', visualPriorityReportDir, ...
        'CableAccelVisualPriorityReport_%s_20260301_20260331.jpg', points)
    checkImageSet('low_keep_vs_extreme_low_keep_images', ...
        lowKeepVsExtremeDir, 'LowKeepAuto_%s_20260301_20260331.jpg', points)
    checkImageSet('low_keep_vs_extreme_extreme_images', ...
        lowKeepVsExtremeDir, 'ExtremeFallback_%s_20260301_20260331.jpg', points)
    checkImageSet('target60_images', ...
        fullfile(stableDir, 'target60_display_export'), ...
        'CableAccelTarget60Display_%s_20260301_20260331.jpg', points)
    checkImageSet('target50_images', ...
        fullfile(stableDir, 'target50_display_export'), ...
        'CableAccelTarget50Display_%s_20260301_20260331.jpg', points)
    checkImageSet('cleanest60_images', ...
        fullfile(stableDir, 'cleanest60_display_export'), ...
        'CableAccelCleanest60Display_%s_20260301_20260331.jpg', points)
    checkImageSet('cleanest50_images', ...
        fullfile(stableDir, 'cleanest50_display_export'), ...
        'CableAccelCleanest50Display_%s_20260301_20260331.jpg', points)
    checkRequiredFile('cleanest70_report_contact_sheet', ...
        fullfile(cleanest70ReportDir, 'CableAccelCleanest70Report_ContactSheet.jpg'))
    checkRequiredFile('cleanest70_report_review_board', ...
        fullfile(cleanest70ReportDir, 'CableAccelCleanest70Report_ReviewBoard.jpg'))
    checkRequiredFile('satisfaction_auto_report_contact_sheet', ...
        fullfile(satisfactionAutoReportDir, ...
        'CableAccelSatisfactionAutoReport_ContactSheet.jpg'))
    checkRequiredFile('satisfaction_auto_report_review_board', ...
        fullfile(satisfactionAutoReportDir, ...
        'CableAccelSatisfactionAutoReport_ReviewBoard.jpg'))
    checkRequiredFile('low_keep_auto_report_contact_sheet', ...
        fullfile(lowKeepAutoReportDir, ...
        'CableAccelLowKeepAutoReport_ContactSheet.jpg'))
    checkRequiredFile('low_keep_auto_report_review_board', ...
        fullfile(lowKeepAutoReportDir, ...
        'CableAccelLowKeepAutoReport_ReviewBoard.jpg'))
    checkRequiredFile('extreme_fallback_report_contact_sheet', ...
        fullfile(extremeFallbackReportDir, ...
        'CableAccelExtremeFallbackReport_ContactSheet.jpg'))
    checkRequiredFile('extreme_fallback_report_review_board', ...
        fullfile(extremeFallbackReportDir, ...
        'CableAccelExtremeFallbackReport_ReviewBoard.jpg'))
    checkRequiredFile('hybrid_recommended_report_contact_sheet', ...
        fullfile(hybridRecommendedReportDir, ...
        'CableAccelHybridRecommendedReport_ContactSheet.jpg'))
    checkRequiredFile('hybrid_recommended_report_review_board', ...
        fullfile(hybridRecommendedReportDir, ...
        'CableAccelHybridRecommendedReport_ReviewBoard.jpg'))
    checkRequiredFile('refined55_report_contact_sheet', ...
        fullfile(refined55ReportDir, ...
        'CableAccelRefined55Report_ContactSheet.jpg'))
    checkRequiredFile('refined55_report_review_board', ...
        fullfile(refined55ReportDir, ...
        'CableAccelRefined55Report_ReviewBoard.jpg'))
    checkRequiredFile('auto_visual_report_contact_sheet', ...
        fullfile(autoVisualReportDir, ...
        'CableAccelAutoVisualReport_ContactSheet.jpg'))
    checkRequiredFile('auto_visual_report_review_board', ...
        fullfile(autoVisualReportDir, ...
        'CableAccelAutoVisualReport_ReviewBoard.jpg'))
    checkRequiredFile('satisfaction_review_board', ...
        fullfile(stableDir, 'satisfaction_review', ...
        'CableAccelSatisfactionReview_Board.jpg'))
    checkRequiredFile('low_keep_tradeoff_board', ...
        fullfile(stableDir, 'low_keep_tradeoff_review', ...
        'CableAccelLowKeepTradeoff_Board.jpg'))
    checkRequiredFile('low_keep_vs_extreme_board', ...
        fullfile(lowKeepVsExtremeDir, 'CableAccelLowKeepVsExtreme_Board.jpg'))
    checkRequiredFile('hybrid_recommended_parameters_json', ...
        fullfile(hybridRecommendedParametersDir, ...
        'CableAccelHybridRecommended_parameters.json'))
    checkRequiredFile('refined55_parameters_json', ...
        fullfile(refined55ParametersDir, ...
        'CableAccelRefined55_parameters.json'))
    checkRequiredFile('auto_visual_parameters_json', ...
        fullfile(autoVisualSearchDir, ...
        'CableAccelAutoVisualSearch_parameters.json'))
    checkRequiredFile('auto_visual_review_summary_json', ...
        fullfile(autoVisualReviewDir, ...
        'CableAccelAutoVisualReview_summary.json'))
    checkRequiredFile('auto_visual_review_board', ...
        fullfile(autoVisualReviewDir, ...
        'CableAccelAutoVisualReview_Board.jpg'))
    checkRequiredFile('ultra_clean_summary_json', ...
        fullfile(ultraCleanReviewDir, ...
        'CableAccelUltraCleanReview_summary.json'))
    checkRequiredFile('ultra_clean_full_shortlist_csv', ...
        fullfile(ultraCleanReviewDir, ...
        'CableAccelUltraCleanReview_full_shortlist.csv'))
    checkRequiredFile('ultra_clean_board', ...
        fullfile(ultraCleanReviewDir, ...
        'CableAccelUltraCleanReview_Board.jpg'))
    checkRequiredFile('ultra_clean_contact_sheet', ...
        fullfile(ultraCleanReviewDir, ...
        'CableAccelUltraCleanPackage_ContactSheet.jpg'))
    checkRequiredFile('strict_report_summary_json', ...
        fullfile(strictReportDir, 'CableAccelStrictReport_summary.json'))
    checkRequiredFile('strict_report_contact_sheet', ...
        fullfile(strictReportDir, 'CableAccelStrictReport_ContactSheet.jpg'))
    checkRequiredFile('strict_report_compare_board', ...
        fullfile(strictReportDir, 'CableAccelStrictReport_CompareBoard.jpg'))
    checkRequiredFile('strict_final_report_summary_json', ...
        fullfile(strictFinalReportDir, ...
        'CableAccelStrictFinalReport_summary.json'))
    checkRequiredFile('strict_final_report_contact_sheet', ...
        fullfile(strictFinalReportDir, ...
        'CableAccelStrictFinalReport_ContactSheet.jpg'))
    checkRequiredFile('strict_final_report_review_board', ...
        fullfile(strictFinalReportDir, ...
        'CableAccelStrictFinalReport_ReviewBoard.jpg'))
    checkRequiredFile('visual_priority_report_summary_json', ...
        fullfile(visualPriorityReportDir, ...
        'CableAccelVisualPriorityReport_summary.json'))
    checkRequiredFile('visual_priority_report_contact_sheet', ...
        fullfile(visualPriorityReportDir, ...
        'CableAccelVisualPriorityReport_ContactSheet.jpg'))
    checkRequiredFile('visual_priority_report_compare_board', ...
        fullfile(visualPriorityReportDir, ...
        'CableAccelVisualPriorityReport_CompareBoard.jpg'))
    checkRequiredFile('cleaner_report_contact_sheet', ...
        fullfile(cleanerReportDir, 'CableAccelDecisiveVisualReport_ContactSheet.jpg'))
    checkRequiredFile('cleaner_report_review_board', ...
        fullfile(cleanerReportDir, 'CableAccelDecisiveVisualReport_ReviewBoard.jpg'))
    checkRequiredFile('current_best_acceptance_json', ...
        fullfile(stableDir, 'current_best_acceptance.json'))
    checkRequiredFile('current_best_summary_json', ...
        fullfile(stableDir, 'CableAccelCurrentBestDisplay_summary.json'))
    checkRequiredFile('final_display_summary_json', ...
        fullfile(stableDir, 'CableAccelFinalDisplay_summary.json'))
    checkRequiredFile('current_best_report_index', fullfile(currentReportDir, 'index.html'))
    checkRequiredFile('cleaner_report_index', fullfile(cleanerReportDir, 'index.html'))];
fileChecks = [
    fileChecks
    checkRequiredFile('cleanest70_report_index', fullfile(cleanest70ReportDir, 'index.html'))
    checkRequiredFile('satisfaction_auto_report_index', ...
        fullfile(satisfactionAutoReportDir, 'index.html'))
    checkRequiredFile('low_keep_auto_report_index', ...
        fullfile(lowKeepAutoReportDir, 'index.html'))
    checkRequiredFile('extreme_fallback_report_index', ...
        fullfile(extremeFallbackReportDir, 'index.html'))
    checkRequiredFile('hybrid_recommended_report_index', ...
        fullfile(hybridRecommendedReportDir, 'index.html'))
    checkRequiredFile('refined55_report_index', ...
        fullfile(refined55ReportDir, 'index.html'))
    checkRequiredFile('auto_visual_report_index', ...
        fullfile(autoVisualReportDir, 'index.html'))
    checkRequiredFile('low_keep_tradeoff_index', ...
        fullfile(stableDir, 'low_keep_tradeoff_review', 'index.html'))
    checkRequiredFile('low_keep_vs_extreme_index', ...
        fullfile(lowKeepVsExtremeDir, 'index.html'))
    checkRequiredFile('hybrid_recommended_parameters_index', ...
        fullfile(hybridRecommendedParametersDir, 'index.html'))
    checkRequiredFile('refined55_parameters_index', ...
        fullfile(refined55ParametersDir, 'index.html'))
    checkRequiredFile('auto_visual_search_index', ...
        fullfile(autoVisualSearchDir, 'index.html'))
    checkRequiredFile('auto_visual_review_index', ...
        fullfile(autoVisualReviewDir, 'index.html'))
    checkRequiredFile('ultra_clean_review_index', ...
        fullfile(ultraCleanReviewDir, 'index.html'))
    checkRequiredFile('strict_report_index', ...
        fullfile(strictReportDir, 'index.html'))
    checkRequiredFile('strict_final_report_index', ...
        fullfile(strictFinalReportDir, 'index.html'))
    checkRequiredFile('visual_priority_report_index', ...
        fullfile(visualPriorityReportDir, 'index.html'))
    checkRequiredFile('satisfaction_review_index', ...
        fullfile(stableDir, 'satisfaction_review', 'index.html'))];

pagePaths = { ...
    fullfile(stableDir, 'current_best_index.html');
    fullfile(stableDir, 'final_index.html');
    fullfile(stableDir, 'index.html');
    fullfile(stableDir, 'satisfaction_review', 'index.html');
    fullfile(stableDir, 'three_level_tradeoff_review', 'index.html');
    fullfile(stableDir, 'retention_tradeoff_summary', 'index.html');
    fullfile(stableDir, 'visual_best_display_export', 'index.html');
    fullfile(stableDir, 'decisive_visual_display_export', 'index.html');
    fullfile(stableDir, 'cleanest70_display_export', 'index.html');
    fullfile(stableDir, 'cleanest60_display_export', 'index.html');
    fullfile(stableDir, 'cleanest50_display_export', 'index.html');
    fullfile(stableDir, 'target80_display_export', 'index.html');
    fullfile(stableDir, 'target75_display_export', 'index.html');
    fullfile(stableDir, 'target70_display_export', 'index.html');
    fullfile(stableDir, 'target60_display_export', 'index.html');
    fullfile(stableDir, 'target50_display_export', 'index.html');
    fullfile(stableDir, 'low_keep_tradeoff_review', 'index.html');
    fullfile(stableDir, 'low_keep_vs_extreme_report', 'index.html');
    fullfile(stableDir, 'hybrid_recommended_parameters', 'index.html');
    fullfile(stableDir, 'refined55_parameters', 'index.html');
    fullfile(stableDir, 'auto_visual_search', 'index.html');
    fullfile(stableDir, 'auto_visual_review', 'index.html');
    fullfile(stableDir, 'ultra_clean_review', 'index.html');
    fullfile(stableDir, 'strict_report_candidate', 'index.html');
    fullfile(strictFinalReportDir, 'index.html');
    fullfile(visualPriorityReportDir, 'index.html');
    fullfile(currentReportDir, 'index.html');
    fullfile(cleanerReportDir, 'index.html');
    fullfile(cleanest70ReportDir, 'index.html');
    fullfile(satisfactionAutoReportDir, 'index.html');
    fullfile(lowKeepAutoReportDir, 'index.html');
    fullfile(extremeFallbackReportDir, 'index.html');
    fullfile(hybridRecommendedReportDir, 'index.html');
    fullfile(refined55ReportDir, 'index.html');
    fullfile(autoVisualReportDir, 'index.html')};
[pageChecks, pagesOk] = checkLinkedPages(pagePaths);

formalConfigOk = hasFormalCableAccelPolicy(cfg);
overallPass = formalConfigOk && all(fileChecks.Pass) && pagesOk;

globalChecks = table( ...
    {'formal_config_daily_median_abs100'; 'required_files_ok'; ...
     'html_links_and_images_ok'}, ...
    [formalConfigOk; all(fileChecks.Pass); pagesOk], ...
    'VariableNames', {'Check','Pass'});

validationXlsx = fullfile(stableDir, 'CableAccelVisualAlternatives_validation.xlsx');
validationJson = fullfile(stableDir, 'CableAccelVisualAlternatives_validation.json');
validationHtml = fullfile(stableDir, 'visual_alternatives_validation.html');
writetable(globalChecks, validationXlsx, 'Sheet', 'global_checks');
writetable(fileChecks, validationXlsx, 'Sheet', 'file_checks');
writetable(pageChecks, validationXlsx, 'Sheet', 'page_checks');
writeJson(validationJson, overallPass, globalChecks, fileChecks, pageChecks);
writeHtml(validationHtml, overallPass, globalChecks, fileChecks, pageChecks);

result = struct();
result.pass = overallPass;
result.global_checks = globalChecks;
result.file_checks = fileChecks;
result.page_checks = pageChecks;
result.workbook = validationXlsx;
result.json = validationJson;
result.html = validationHtml;

fprintf('visual alternatives validation pass: %d\n', overallPass);
fprintf('workbook %s\n', validationXlsx);
fprintf('html %s\n', validationHtml);
disp(globalChecks);
disp(fileChecks);
end

function row = checkCsvRows(label, path, expectedRows)
pass = false;
detail = '';
if isfile(path)
    try
        T = readtable(path, 'Encoding', 'UTF-8');
        actualRows = height(T);
        pass = actualRows == expectedRows;
        detail = sprintf('rows=%d expected=%d', actualRows, expectedRows);
    catch ME
        detail = ME.message;
    end
else
    detail = 'missing file';
end
row = table({label}, {path}, pass, {detail}, ...
    'VariableNames', {'Check','Path','Pass','Detail'});
end

function row = checkStrictFinalRules(label, path)
pass = false;
detail = '';
expectedPoints = {'CF-1','CF-2','CF-3','CF-4','CF-5','CF-6','CF-7','CF-8'};
expectedSources = {'auto_visual_default','strict_ultra_clean', ...
    'auto_visual_default','auto_visual_default','strict_score_matrix', ...
    'auto_visual_default','strict_ultra_clean','strict_score_matrix'};
if isfile(path)
    try
        T = readtable(path, 'Encoding', 'UTF-8');
        sourceOk = false(numel(expectedPoints), 1);
        for i = 1:numel(expectedPoints)
            idx = find(strcmp(string(T.PointID), expectedPoints{i}), 1);
            sourceOk(i) = ~isempty(idx) && ...
                strcmp(string(T.SelectedSource(idx)), expectedSources{i});
        end
        pass = height(T) == 8 && all(sourceOk);
        detail = sprintf('strict_sources_ok=%d rows=%d', all(sourceOk), height(T));
    catch ME
        detail = ME.message;
    end
else
    detail = 'missing file';
end
row = table({label}, {path}, pass, {detail}, ...
    'VariableNames', {'Check','Path','Pass','Detail'});
end

function row = checkImageSet(label, folder, pattern, points)
missing = 0;
small = 0;
for i = 1:numel(points)
    path = fullfile(folder, sprintf(pattern, points{i}));
    if ~isfile(path)
        missing = missing + 1;
    elseif dirBytes(path) < 10000
        small = small + 1;
    end
end
pass = missing == 0 && small == 0;
detail = sprintf('points=%d missing=%d small=%d', numel(points), missing, small);
row = table({label}, {folder}, pass, {detail}, ...
    'VariableNames', {'Check','Path','Pass','Detail'});
end

function row = checkRequiredFile(label, path)
pass = isfile(path) && dirBytes(path) > 0;
detail = sprintf('bytes=%d', dirBytes(path));
if ~isfile(path)
    detail = 'missing file';
end
row = table({label}, {path}, pass, {detail}, ...
    'VariableNames', {'Check','Path','Pass','Detail'});
end

function [rows, ok] = checkLinkedPages(pages)
rowData = {};
ok = true;
for i = 1:numel(pages)
    page = pages{i};
    if ~isfile(page)
        rowData(end+1, :) = {page, 0, 0, 0, 0, false, 'missing page'}; %#ok<AGROW>
        ok = false;
        continue;
    end
    [imageRefs, missingImages, hrefs, missingHrefs] = checkPage(page);
    pass = missingImages == 0 && missingHrefs == 0;
    ok = ok && pass;
    rowData(end+1, :) = {page, imageRefs, missingImages, hrefs, ...
        missingHrefs, pass, 'ok'}; %#ok<AGROW>
end
rows = cell2table(rowData, 'VariableNames', { ...
    'Page','ImageRefs','MissingImages','HrefRefs','MissingHrefs','Pass','Detail'});
end

function [imageRefs, missingImages, hrefRefs, missingHrefs] = checkPage(page)
text = fileread(page);
baseDir = fileparts(page);
imgTokens = regexp(text, '<img[^>]+src="([^"]+)"', 'tokens');
hrefTokens = regexp(text, 'href="([^"]+)"', 'tokens');
imageRefs = numel(imgTokens);
hrefRefs = 0;
missingImages = 0;
missingHrefs = 0;
for i = 1:numel(imgTokens)
    if ~localTargetExists(baseDir, imgTokens{i}{1})
        missingImages = missingImages + 1;
    end
end
for i = 1:numel(hrefTokens)
    href = hrefTokens{i}{1};
    if startsWith(href, 'http:') || startsWith(href, 'https:') || ...
            startsWith(href, 'mailto:') || startsWith(href, '#')
        continue;
    end
    hrefRefs = hrefRefs + 1;
    if ~localTargetExists(baseDir, href)
        missingHrefs = missingHrefs + 1;
    end
end
end

function ok = localTargetExists(baseDir, rel)
rel = strrep(rel, '/', filesep);
target = char(java.io.File(baseDir, rel).getCanonicalPath());
ok = exist(target, 'file') == 2 || exist(target, 'dir') == 7;
end

function ok = hasFormalCableAccelPolicy(cfg)
ok = false;
try
    thresholds = cfg.defaults.cable_accel.thresholds;
    if isempty(thresholds)
        return;
    end
    first = thresholds(1);
    hasBounds = isfield(first, 'min') && isfield(first, 'max') && ...
        abs(first.min + 100) < 1e-9 && abs(first.max - 100) < 1e-9;
    hasOffset = isfield(cfg.defaults.cable_accel, 'offset_correction') && ...
        isfield(cfg.defaults.cable_accel.offset_correction, 'mode') && ...
        strcmp(cfg.defaults.cable_accel.offset_correction.mode, 'daily_median');
    ok = hasBounds && hasOffset;
catch
    ok = false;
end
end

function writeJson(path, overallPass, globalChecks, fileChecks, pageChecks)
data = struct();
data.generated_at = datestr(now, 'yyyy-mm-dd HH:MM:SS');
data.pass = overallPass;
data.global_checks = table2struct(globalChecks);
data.file_checks = table2struct(fileChecks);
data.page_checks = table2struct(pageChecks);
fid = fopen(path, 'w', 'n', 'UTF-8');
cleaner = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', jsonencode(data));
end

function writeHtml(path, overallPass, globalChecks, fileChecks, pageChecks)
fid = fopen(path, 'w', 'n', 'UTF-8');
cleaner = onCleanup(@() fclose(fid));
fprintf(fid, '<!doctype html>\n<html lang="zh-CN">\n<head>\n<meta charset="utf-8">\n');
fprintf(fid, '<title>Zhishan Cable Acceleration Visual Alternative Validation</title>\n');
fprintf(fid, '<style>');
fprintf(fid, 'body{font-family:Arial,"Microsoft YaHei",sans-serif;margin:24px;color:#172033;background:#f7f8fa;}');
fprintf(fid, 'h1{font-size:24px;margin:0 0 10px;} h2{font-size:18px;margin:28px 0 12px;} .pass{color:#067a46;font-weight:700;} .fail{color:#b42318;font-weight:700;}');
fprintf(fid, 'table{border-collapse:collapse;background:white;width:100%%;margin:12px 0 22px;} th,td{border:1px solid #d7dce2;padding:7px 9px;text-align:left;font-size:13px;} th{background:#eef2f6;} .num{text-align:right;font-variant-numeric:tabular-nums;}');
fprintf(fid, '</style>\n</head>\n<body>\n');
cls = 'fail';
if overallPass, cls = 'pass'; end
fprintf(fid, '<h1>Zhishan Cable Acceleration Visual Alternative Validation</h1>\n');
fprintf(fid, '<p>Overall pass: <span class="%s">%d</span></p>\n', cls, overallPass);
fprintf(fid, '<h2>Global Checks</h2><table><tr><th>Check</th><th>Pass</th></tr>\n');
for i = 1:height(globalChecks)
    fprintf(fid, '<tr><td>%s</td><td class="num">%d</td></tr>\n', ...
        htmlText(globalChecks.Check{i}), globalChecks.Pass(i));
end
fprintf(fid, '</table>\n<h2>File Checks</h2><table>\n');
fprintf(fid, '<tr><th>Check</th><th>Path</th><th>Pass</th><th>Detail</th></tr>\n');
for i = 1:height(fileChecks)
    fprintf(fid, '<tr><td>%s</td><td>%s</td><td class="num">%d</td><td>%s</td></tr>\n', ...
        htmlText(fileChecks.Check{i}), htmlText(fileChecks.Path{i}), ...
        fileChecks.Pass(i), htmlText(fileChecks.Detail{i}));
end
fprintf(fid, '</table>\n<h2>Page Checks</h2><table>\n');
fprintf(fid, '<tr><th>Page</th><th>Image refs</th><th>Missing images</th><th>Hrefs</th><th>Missing hrefs</th><th>Pass</th><th>Detail</th></tr>\n');
for i = 1:height(pageChecks)
    fprintf(fid, '<tr><td>%s</td><td class="num">%d</td><td class="num">%d</td><td class="num">%d</td><td class="num">%d</td><td class="num">%d</td><td>%s</td></tr>\n', ...
        htmlText(pageChecks.Page{i}), pageChecks.ImageRefs(i), ...
        pageChecks.MissingImages(i), pageChecks.HrefRefs(i), ...
        pageChecks.MissingHrefs(i), pageChecks.Pass(i), ...
        htmlText(pageChecks.Detail{i}));
end
fprintf(fid, '</table>\n</body>\n</html>\n');
end

function bytes = dirBytes(path)
d = dir(path);
if isempty(d)
    bytes = 0;
else
    bytes = d(1).bytes;
end
end

function out = htmlText(value)
out = char(string(value));
out = strrep(out, '&', '&amp;');
out = strrep(out, '<', '&lt;');
out = strrep(out, '>', '&gt;');
out = strrep(out, '"', '&quot;');
end
